### ISSUE TITLE
GetOrAdd capability

### ISSUE THREAD

**Issue by bluefox** [MichaCo/CacheManager#10]
I think a GetOrAdd function would be useful, as mentioned in the distributed environment it is necessary to make sure all caches are in sync. The function would basically add the value to the key/region only when the key doesn't already exists.

Perhaps something that looks like the following?

```
        private TCacheValue GetOrAddInternal(string key, string region, Func<CacheItem<TCacheValue>> itemFunc)
        {
            var item = string.IsNullOrWhiteSpace(region) ? GetCacheItem(key) : GetCacheItem(key, region);

            // if the cache item doesn't already exist, add them
            if (item == null)
            {
                item = itemFunc();
                AddInternal(item);
            }

            return item.Value;
        }
```

**Comment by MichaCo** [comment]
Yup sounds good, feel free to push a pull request :smiley_cat:  (please with unit tests,, testing and documentation in code)
