### ISSUE TITLE
Question: what happens if I exceed available server memory?

### ISSUE THREAD

**Issue by Korayem** [MichaCo/CacheManager#102]
Does CacheManager automatically force delete old items even if they didn't expire? I am using `SystemRuntimeCaching.MemoryCacheHandle`

And does CacheManager manage the memory allocation in any way, or it deals with its cache provider as a blackbox?

**Comment by TMiNus** [comment]
Actually it throws an ```OutOfMemory`` exception, there are some bugs in ```MemoryCacheHandle`` where it doesn't trim the memory correctly.

**Comment by MichaCo** [comment]
@Korayem all caching technologies supported by CacheManager provide some way of handling memory pressure and/or upper limits, except the build in dictionary cache which would eventually run out of memory.
If the underlying implementation is buggy as @TMiNus mentioned, CacheManager will not do anything to work around it atm.

**Comment by Korayem** [comment]
ok thanks for the insights

I will look into hooking to `SystemRuntimeCaching.MemoryCacheHandle` to detect and fix it's memory usage

Thanks!
