### ISSUE TITLE
Does ClearRegion work on Memcached handles?

### ISSUE THREAD

**Issue by themakshter** [MichaCo/CacheManager#103]
Memcached does not really handle namespaces nor does it have any easy way of dealing with clearing a particular namespace. But is this being dealt with on CacheManager?

**Comment by themakshter** [comment]
Just went through the code, saw the remarks that it isn't supported right now lol. Whoops, closing the issue.

However, will you be thinking about addressing this or implementing this?

**Comment by MichaCo** [comment]
Yup that's correct, its not supported easily with memchaced. I didn't look into that for a long time so currently I don't have plans to extend on that. Happy to take pull requests though ;)
