### ISSUE TITLE
Guidance on using the outputcache and the cachemanager cache in business layer

### ISSUE THREAD

**Issue by sbosell** [MichaCo/CacheManager#106]
Do you have any guidance on using the outputcache and cache together?  

For instance if there is an output cache on a page that displays a table of objects and the user creates a new object the output cache should be invalidated. In my example the data layer is caching the individual object and not the controller and I'd prefer to invalidate the output cache in the data layer.

**Comment by MichaCo** [comment]
I don't really get what you are trying to do or what you need guidance on, maybe you should post some code examples on stackoverflow

**Comment by sbosell** [comment]
Which part of my question isn't clear?  Web [outputcache] using cachemanager.net on an action in a controller being invalidated by the cachemanager in the business or data layer.    I'll post on SO as well.

**Comment by MichaCo** [comment]
If you are using the outputcache attribute, the ASP.NET framework doesn't provide a simple way to access the underlying cache. Our custom attribute though has a static field to the CacheManager instance, I think that's the only way atm to call `Clear` for example.

**Comment by MichaCo** [comment]
@sbosell let me know if you still having issues with this. Closing this for now.
