### ISSUE TITLE
New to CacheManager and Unity

### ISSUE THREAD

**Issue by HarleeDavidson** [MichaCo/CacheManager#110]
Hi,

I am using CacheManager in a web API, it is configured similar to the todo examples and working nicely in APi Controllers. How can I configure it to work in my lower tier service objects?

Thank you.

**Comment by MichaCo** [comment]
If you inject your "lower tier service objects" you can use the DI framework to inject the cache to anything you want. If you don't use DI, make sure you use a singleton somewhere.
This is not really related to CacheManager though, just standard coding / design patterns ;)
/closing
