### ISSUE TITLE
Using JsonSerializer with SerializerOptions is problematic

### ISSUE THREAD

**Issue by rebulanyum** [MichaCo/CacheManager#112]
Hi again.

Consider that I've used the following code in order to create a cache

    var cache = CacheFactory.Build<object>("MyCache", cbcp =>
            {
                var serializerSetting = new Newtonsoft.Json.JsonSerializerSettings();
                serializerSetting.Converters.Add(new CustomCollectionJsonConverter());
                cbcp.WithSystemRuntimeCacheHandle("cache1")
                    .And
                    .WithJsonSerializer(null, serializerSetting)
                    .WithRedisConfiguration("redis", rcb =>
                    {
                        rcb.WithEndpoint(redisUrl, redisPort)
                           .WithDatabase(redisDatabaseId)
                    })
                    .WithRedisBackplane("redis")
                    .WithRedisCacheHandle("redis", true) ;
            });

On line 4 I gave the custom json deserialization settings: expecing to make this work only on deserialization process. However, it's working on both serialization and deserialization processes. After debugging found the error on [CacheReflectionHelper.cs:207](https://github.com/MichaCo/CacheManager/blob/dev/src/CacheManager.Core/Internal/CacheReflectionHelper.cs#L207). This piece of code creates types according to the parameters that matches the types of arguments; not trying to match the order of the parameters or arguments at all. Since WithJsonSerializer method has 2 parameters with the same type it really doesn't matter if you put the parameter into 1st or 2nd argument at all.

**Comment by MichaCo** [comment]
That looks like a but, thanks!

**Comment by MichaCo** [comment]
Should be fixed in next release

**Comment by MichaCo** [comment]
@rebulanyum 
Version 0.9.2 is out and should fix this issue. Let me know if that's not the case though ;)
