### ISSUE TITLE
Load Configuration via json string

### ISSUE THREAD

**Issue by radleta** [MichaCo/CacheManager#119]
I'd really like to load the configuration via a json string. I'm NOT using .NET Core. 

Is there any way to do this?

**Comment by MichaCo** [comment]
It should work the same was as with .net core, just install the nuget packages needed.

One of my test projects on https://github.com/MichaCo/CacheManager.CI/tree/master/src/ConsoleApp actually does that for example https://github.com/MichaCo/CacheManager.CI/blob/master/src/ConsoleApp/Program.cs#L49

**Comment by radleta** [comment]
@MichaCo Thanks! I'll take a look and give it a try.
