### ISSUE TITLE
Redis 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll

### ISSUE THREAD

**Issue by Eneuman** [MichaCo/CacheManager#122]
Hi!

I'm trying using redis as a backplane but am receiving the following error.
An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll
No stacktrace other then the above.
Sometimes it works and sometimes it craches.

In my log, it always stops at the following line:
CacheManager.Redis.RedisConnectionManager:Debug: BeginConnect: xxxxx.redis.cache.windows.net:6380
CacheManager.Redis.RedisConnectionManager:Debug: 1 unique nodes specified
CacheManager.Redis.RedisConnectionManager:Debug: Requesting tie-break from xxxxx.redis.cache.windows.net:6380 > __Booksleeve_TieBreak...
CacheManager.Redis.RedisConnectionManager:Debug: Allowing endpoints 00:00:05 to respond...
CacheManager.Redis.RedisConnectionManager:Debug: EndConnect: xxxxx.redis.cache.windows.net:6380
CacheManager.Redis.RedisConnectionManager:Debug: Configuring SSL

and then debugging crashes with the exception above.

Any idea on how to debug this error ?

Regards
Per

**Comment by MichaCo** [comment]
After researching this a little bit I came across this issue in [corefx]( https://github.com/dotnet/coreclr/issues/8148 ) and a workaround described here: https://github.com/dotnet/corefx/issues/13814. 
Not sure if that helps at all though as I cannot reproduce your stuff without setting up a similar environment. 
Anyways, if the above workaround doesn't help, could you post all information? like project.json, configuration, dotnet --version, environment (windows/linux version)? (don't post passwords or stuff like that though ;) )

**Comment by MichaCo** [comment]
@Eneuman So, I just gave it a try and did setup a test project against a MS Azure Redis instance.
I tested it with .NET full framework, .NET Core netcoreapp1.0 and netcoreapp1.1; with and without backplane.

Worked every time without any issues.

Can you at least show me how you configure the connection to the azure redis instance?
In general you just use the ssl port 6380 and set the password to one of your access keys, and that should be it.

**Comment by Eneuman** [comment]
Hi and thanks for your quick answer.
I have the following configuration:

```
      // Create cache configuration
      var cacheConfig = new CacheManager.Core.ConfigurationBuilder()
        .WithMicrosoftLogging(f =>
        {
          f.AddConsole(LogLevel.Information);
          f.AddDebug(LogLevel.Trace);
        })
        .WithJsonSerializer()
        .WithMicrosoftMemoryCacheHandle("inprocess")
        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))
        .And
        .WithRedisConfiguration("redis.azure", "xxxx.redis.cache.windows.net:6380,password=xxxx,ssl=True,abortConnect=False")
        .WithRedisBackplane("redis.azure")
        .WithRedisCacheHandle("redis.azure", true)
        .Build();

      services.AddSingleton(cacheConfig);

      // Add the cache manager interface and impl type as open generics
      services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
```

I have also created the following extension method:
```
 public static class CacheManagerExtensions
  {
    public static async Task<TCacheValue> GetOrAddAsync<TCacheValue>(this ICacheManager<TCacheValue> cacheManager, string key, string region, Func<string, string, Task<TCacheValue>> valueFactoryAsync)
    {
      var tries = 0;
      do
      {
        tries++;
        var item = cacheManager.GetCacheItem(key, region);
        if (item != null)
        {
          return item.Value;
        }

        var newValue = await valueFactoryAsync(key, region);

        // Throw explicit to me more consistent. Otherwise it would throw later eventually...
        if (newValue == null)
        {
          throw new InvalidOperationException("The value which should be added must not be null.");
        }

        item = string.IsNullOrWhiteSpace(region) ? new CacheItem<TCacheValue>(key, newValue) : new CacheItem<TCacheValue>(key, region, newValue);
        if (cacheManager.Add(item))
        {
          return newValue;
        }
      }
      while (tries <= cacheManager.Configuration.MaxRetries);

      // should usually never occur, but could if e.g. max retries is 1 and an item gets added between the get and add.
      // pretty unusual, so keep the max tries at least around 50
      throw new InvalidOperationException(string.Format("Could not get nor add the item {0} {1}", key, region));
    }
  }
```

That im using like this:
```
      var value = await _cacheManagerString.GetOrAddAsync("GetUserInfoAsync_" + uniktId, "Tenant" + tenantId, async (key, region) =>
      {
        return await _dbContext.Users.Where(ap => u.Id == id).Select(a => u.Name).FirstOrDefaultAsync();
      });

```

I'm gonna try the suggested fix for the corefx bug, I have a feeling that this whats happening to us aswell. The error is very similar and we are also using Certificates heavily. Thanks for the link!
I'll post my results as soon as possible.,

**Comment by Eneuman** [comment]
I found that commenting out the following rows makes the error go away.

```
        .And
        .WithRedisConfiguration("redis.azure", "xxx.redis.cache.windows.net:6380,password=xxxx,ssl=True,abortConnect=False")
        .WithRedisBackplane("redis.azure")
        .WithRedisCacheHandle("redis.azure", true)
```

**Comment by MichaCo** [comment]
Configuration looks fine, I used pretty much the same for testing in a console app and web.api connecting to my managed redis services on ...redis.cache.windows.net:6380. And it just works fine.

Yeah ofc it will work if you comment out the redis related stuff. Problem is clearly the SSL binding done by the StackExchange.Redis package (at least according to the log file you posted).

Can you check your `dotnet --version`? I have 1.0.0-preview2-1-003177 installed, which is v 1.1.0.
Also, make sure you are not mixing 1.0.0 with 1.1.0 versions of System.* packages and use the right Microsoft.NETCore.App version. Could eventually cause issues, too.

But to be totally honest, I have no idea why the SSL configuration for me just works fine and you get an exception...

**Comment by Eneuman** [comment]
I found the problem :)
It's already been logged in the coreclr repo under [here](https://github.com/dotnet/coreclr/issues/8477)
I'm gonna close this issue but thank you soo much for trying to debug this!

**Comment by MichaCo** [comment]
Nice!  Yeah it seems to link to another issue I found earlier... Happy testing ;)
