### ISSUE TITLE
Failed to initialize instance of type CacheManager.Redis.RedisCacheHandle~1[System.String]

### ISSUE THREAD

**Issue by youliny** [MichaCo/CacheManager#124]
Hi MichaCo ,The problem is occur when i update my version of Cachemanager from 0.90 to 0.92 . i use the in-memory  cache, and the redis as the backplane. when the application run for a period of time. it will throw the exception:Failed to initialize instance of type CacheManager.Redis.RedisCacheHandle~1[System.String](the type of cache item is string that serilized from list<T> ).
and the inner message is that: could not to load StackExchange.Redis.StrongName. Looking forward to your help。

**Comment by MichaCo** [comment]
@youliny 
The error simply means that the dependency to StackExchange.Redis is not installed.

The reference to the external library StackExchange.Redis changed from 0.9 to 0.9.2. I'm not using the unsigned package anymore and unfortunately, StackExchange.Redis has a separated package which is signed with a different name: "StackExchange.Redis.StrongName".

It could be that updating your project to CacheManager 0.9.2 might not have uninstalled the old reference to "StackExchange.Redis" and installed the new one "StackExchange.Redis.StrongName". 
Please try to do that manually. Or try to uninstall CacheManager nugets and install them again and verify that the dependency to StackExchange.Redis.StrongName is properly installed...

**Comment by youliny** [comment]
Like u said ,the version of StackExchange.Redis.StrongName is not consistent with StackExchange.Redis .
thx very much!
