### ISSUE TITLE
using protobuf as a default serializer 

### ISSUE THREAD

**Issue by premsai** [MichaCo/CacheManager#125]
Hi 
How do you configure protobuf as a default serializer for the objects, in the cache.config the known types are only binary and json, i see there is a custom type you can define but I was not successful using it. we are using dotnet core

thanks

Prem

**Comment by MichaCo** [comment]
Just double checked, manually you can configure it by adding the "type" property and set it to "CacheManager.Serialization.ProtoBuf.ProtoBufSerializer, CacheManager.Serialization.ProtoBuf"

However, the next version of CacheManager will support protobuf as known type, too, I added that already some days ago.

**Comment by MichaCo** [comment]
I actually just released the 0.9.3 packages, so you should be able to use the knownType for protobuf now.

**Comment by premsai** [comment]
Thanks it worked
