### ISSUE TITLE
Redis update version token not supported on non lua operations

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#126]
As per 8935dd42d96ffa235b79bb8e004f0c0a1252aa30 redis update operation was changed to use version tokens instead of comparing values, this was done to fix #109. 

Version tokens are not supported in non lua operations making ```Redis_ValidateVersion_AddPutGetUpdate``` fail when ```UseLua``` is set to false on ```RedisCacheHandle``` or the server doesn't support lua

**Comment by MichaCo** [comment]
HI @TMiNus, the test explicitly tests the version changing on each call which changes the key. 
The non lua implementation doesn't use or change the version because it doesn't need it. It uses the transaction feature of the Redis client instead.

On a side note: The transaction stuff has some disadvantages in how reliable it works compared to the lua implementation. But non-lua is only used in case the Redis Server version doesn't support Lua scripting, so, shouldn't be any issue.

**Comment by TMiNus** [comment]
Hi @MichaCo thanks fro the quick response. I failed to notice the transaction part on the non-lua update operation. I haven't looked much into transactions but my understanding is that transactions are mechanism of executing a set of operations in an atomic way, which make sense because we are updating the key and we don't want anyone messing with it

As per [Atomicity of scripts](https://redis.io/commands/eval#atomicity-of-scripts), lua scripts are guarantee to be atomic, so I wonder why are we using a version token in the lua scripts

Can we add a conditional to the test to skip it if lua is not supported on the server?

**Comment by MichaCo** [comment]
@TMiNus lua scripts run atomic but not the code which runs before and after the script. So, between, get, updateFactory() and exec, there can be many updates which increment the version in between... 

No the test doesn't actually need to test this again as the test is done against the features collection internally to switch to non-lua anyways. I'm never running the tests against an actual 2.6 Redis Server, doesn't make sense ;)

**Comment by TMiNus** [comment]
It makes perfect sense.

If this version toek fucntionality is not required in the non lua part I can live with that. My problem being that I actually depend heavily on the non lua part for custom code (I intend to translate it to lua script but... :[ )

One last thing....

I haven't done to much lua scripting but my basic understanding of this piece of code

`if redis.call('HGET', KEYS[1], '{HashFieldVersion}') == ARGV[2] then
    local result=redis.call('HSET', KEYS[1], '{HashFieldValue}', ARGV[1])
    redis.call('HINCRBY', KEYS[1], '{HashFieldVersion}', 1)
    if ARGV[3] == '2' and ARGV[4] ~= '0' then
        redis.call('PEXPIRE', KEYS[1], ARGV[4])
    end
    return result;
else
    return nil
end";

Is that if we are in the middle of the update operation and somehow the key got updated from another place, the current update operation will not be completed, according to his line 

`local result=redis.call('HSET', KEYS[1], '{HashFieldValue}', ARGV[1])` 

Is this assumption correct?

**Comment by MichaCo** [comment]
Yup that's correct, ARGV[2] is the version I retrieved earlier via Get, so, if the version changed between Get and EXEC, the script returns nil indicating an error...

**Comment by TMiNus** [comment]
Makes perfect sense. After the fail it will retry so it's completely fine :). 

Keep up the good work @MichaCo ;)

You can close this one

**Comment by MichaCo** [comment]
Thanks ;)
