### ISSUE TITLE
Generic version of the GetOrAdd API?

### ISSUE THREAD

**Issue by trondd** [MichaCo/CacheManager#128]
It would be nice to have generic versions of the GetOrAdd API. Is there any technical reason for this or simply lack of time?

**Comment by trondd** [comment]
I've made an attempt, but for some reason I can't build the dev branch so I cannot test it:

https://github.com/trondd/CacheManager/tree/feature/genericGetOrAdd

**Comment by MichaCo** [comment]
Mh I don't know of how much use this API gives. The returned object basically just gets cast to another type, that's it. 
And for that we would clutter the apis with more overloads ;)
Also, the casting back and forth is **not** something I'd like to promote too much as it can fail really easily at runtime, which is not really nice.

That being said, you could relatively easily write that as extension methods in your own project

Example:
That even lets you use the factory method with the out parameter and not the original T!

    public static class CustomExtensions
    {
        public static TOut GetOrAdd<T, TOut>(this ICacheManager<T> cache, string key, Func<string, TOut> addFactory)
        {
            Func<string, T> wrapper = (k) => Converter<T>(addFactory(k));

            var v = cache.GetOrAdd(key, wrapper);

            return Converter<TOut>(v);
        }

        public static TOut Converter<TOut>(object value)
        {
            if (value == null)
            {
                return default(TOut);
            }

            try
            {
                object changed = Convert.ChangeType(value, typeof(TOut), CultureInfo.InvariantCulture);
                return changed == null ? (TOut)value : (TOut)changed;
            }
            catch
            {
                return (TOut)value;
            }
        }
    }

can be used like

    var cacheA = new BaseCacheManager<string>(builder.Build());
    var x = cacheA.GetOrAdd("key", (k) => 33);

this casts `int` to `string` and back to `int`.

**Comment by trondd** [comment]
Thanks MichaC, that is an excellent suggestion.
