### ISSUE TITLE
Storing strongly typed classes

### ISSUE THREAD

**Issue by bladefist** [MichaCo/CacheManager#13]
Hello, love your caching manager, trying to learn it and need it to scale.

When I only have the Runtime cache enabled, I can easily add complex classes into cache and retrieve them back as the complex class. It works beautifully.

However, when I enable the redis options, I get serialization error.  My current project has been using the ObjectCache from .Net for so long, and it doesn't require you to do anything with your object, just add/get it to the cache.

Can I use CacheManager to cache these complex objects and not have to serialize/deserialize myself?  

Thanks

**Comment by MichaCo** [comment]
For complex objects and Redis, CacheManager is currently using binary serialization. Which is not really the fastest option, but anyways...
Marking your objects `[Serializable]` should be enough in most cases.

**Comment by bladefist** [comment]
@MichaCo Thanks, that what I was afraid of.  I have gotten Lazy with the ObjectCache, which doesn't require it, now I have a massive project with Caching in tons of places, for objects that are not marked Serializable.

Is there solution, at the CacheManager level?

**Comment by MichaCo** [comment]
Storing objects in process/memory doesn't require serialization. The moment you want to use a distributed cache, you have to serialize the objects. There is no way around ;) 
if you want to store your stuff in Redis or Memcached or any other distributed cache, you have to serialize it, those servers don't know anything about your objects, and we can only store binary data in those scenarios.

If you **don't** want CacheManager to handle serialization for you, you can handle the serialization yourself and then store the byte array or a string, in case you use JSON serialization.
