### ISSUE TITLE
Additional ICacheManager<TCacheValue>.AddOrUpdate() overloads

### ISSUE THREAD

**Issue by jehrenzweig** [MichaCo/CacheManager#130]
I'm just starting to play around with CacheManager, and one of the first things I'm doing is an adding a `CacheItem<object>` to the cache.  However, if it already exists I want to replace what's already in the cache with my new value.

I saw the [two](http://cachemanager.net/Documentation/Index/cachemanager_update#example-1) [examples](http://cachemanager.net/Documentation/Index/cachemanager_update#example-2), but they seem a bit verbose because I'm not looking to do anything clever with the existing cache value.  Here's the code that I'm currently working with in a console app:

```
[Serializable]
public class Test
{
    public string Name { get; set; }
    public int Number { get; set; }
    public SomeOtherType SomethingElse { get; set; }
}

[Serializable]
public class SomeOtherType
{
    public Guid Id { get; set; }
    public DateTime DateTime { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        // var cacheManager = CacheFactory.Build<object>(settings => { ... });

        var testType = new Test { Name = "potato", Number = 42, SomethingElse = new SomeOtherType { Id = Guid.NewGuid(), DateTime = DateTime.Now }};
        var cacheItem = new CacheItem<object>("TestTypeKey", "Region1", testType, ExpirationMode.Sliding, TimeSpan.FromMinutes(30));

        //  Even though I'm not using the [updateValue] parameter, I still have to provide it to the method.
        cacheManager.AddOrUpdate(cacheItem, x => cacheItem.Value);
    }
}
```

What I'd like to do instead is this:
```
        cacheManager.AddOrUpdate(cacheItem);
```

On a related note, it would also be nice to have both the old & new values available in the `updateValue` parameter of the `AddOrUpdate()` method.  For example, if I wanted to use the old value to calculate the new value before applying the update:

```
        var testType = new Test { Name = "potato", Number = 42, SomethingElse = new SomeOtherType { Id = Guid.NewGuid(), DateTime = DateTime.Now }};
        var cacheItem = new CacheItem<object>("TestTypeKey", "Region1", testType, ExpirationMode.Sliding, TimeSpan.FromMinutes(30));

        cacheManager.AddOrUpdate(cacheItem, (oldValue, newValue) => 
        {
                newValue.Number += oldValue.Number;
                return newValue;
        });
```

Please let me know what you think and/or whether it makes sense, and thanks in advance!

**Comment by MichaCo** [comment]
Just use Put instead, that's basically what you are doing.

regarding "(oldValue, newValue)", I don't know the newValue at the point, only you know what this is so there is no way to provide it ;). In case it is a Poco for example, I'd have to clone the old value somehow, so no, that's not possible.

**Comment by jehrenzweig** [comment]
I didn't know about `Put()` -- thank you for pointing me in the right direction.  I will make use of that.

Regarding `(oldValue, newValue)` -- `newValue` is the first parameter I'm already passing to the `AddOrUpdate()` method, while `oldValue` is the object that the `updateValue` parameter already provides you with.  I guess I was thinking it could work similar to how the LINQ `Join()` method works: the first parameter is the object you're looking to join two, and the last parameter is a `Func<>` that allows you to reference both types you're looking to join together.

**Comment by MichaCo** [comment]
That AddOrUpdate is not really comparable to the Enumerable.Job operator... 
Apart from that, if the `newValue` is really the same reference you'd use for `Add`, why'd you use that `AddOrUpdate` method in the first place? That's not the intent. And, on the other hand, you can just keep a reference to it before you call the method and pass it in twice. 

Will close the issue for now as I don't see any need to change anything here.
