### ISSUE TITLE
how to configuration when use redis cluster

### ISSUE THREAD

**Issue by youliny** [MichaCo/CacheManager#131]
just like the topic ,I configuration the redis cluster for the application,three master,three slave .
currently configuration is :`<add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="xxx.xxx.com" accessKey="" ssl="false" />`
so how i should do?

**Comment by MichaCo** [comment]
Cachemanager has nothing todo with that sessionstate provider stuff. If you want to configure redis with CacheManager therer are many examples and docs how to do so

http://cachemanager.net/Documentation/Index/cachemanager_configuration
http://cachemanager.net/Documentation/Index/cachemanager_backed_todo_web_app

via connection string in web.config
https://github.com/MichaCo/CacheManager/blob/dev/test/CacheManager.Tests/Configuration/configuration.valid.allFeatures.config#L5
