### ISSUE TITLE
CacheManager.net is down

### ISSUE THREAD

**Issue by jehrenzweig** [MichaCo/CacheManager#132]
It's been down since at least yesterday morning.  http://isup.me/cachemanager.net

**Comment by MichaCo** [comment]
It is not really down, I'm just moving to a new domain => http://cachemanager.michaco.net

It will take some time till it gets visible on google etc again, but the site is up an its all good ;)

**Comment by jehrenzweig** [comment]
Awesome!  Closing this issue, since it's very much "_by design_". :)
