### ISSUE TITLE
Multiple region support

### ISSUE THREAD

**Issue by getmoble** [MichaCo/CacheManager#135]
I can see that we have region/category option for tge cache. But for me, I think i need multi level category. Because i am planning to use it for multi tenant where i need to cache for a tenant and then  for a category like product. What is an alternative for this use case ?

**Comment by MichaCo** [comment]
How about creating your regions prefixed by tenant?
Like

<tenantKey>_<region>:<actualKey> = <value>

If you need all regions in that tenant, create another key in that region keeping track of that yourself.

I'm trying to keep the "region-feature" of this library as simple as possible. There is already a lot of logic behind it and I'm not going to make it more complex so to say.

Hope that makes sense ;)

**Comment by getmoble** [comment]
ok sure MichaCo, I wanted to know whether i could avoid that region tracking. I will go with your recommendation. Thanks :)
