### ISSUE TITLE
Redis fallback to Runtime Caching

### ISSUE THREAD

**Issue by bladefist** [MichaCo/CacheManager#14]
Does CacheManager have functionality that would allow caching to fall back to runtime caching if the redis server is no longer available?

Thanks!

**Comment by MichaCo** [comment]
No, something like that doesn't really make a lot of sense. Usually those services like Redis do have a very high availability and there are tools to ensure that:
http://redis.io/topics/sentinel
http://redis.io/topics/cluster-tutorial
etc

CacheManager does wait for the Redis server and tries to continue after a connection loss etc...

Do you have any concrete case where you'd have to do that?

**Comment by bladefist** [comment]
@MichaCo No, I just hate to add another failure point in my system. I already have web server, database, azure cloud services, etc.  If any one of those goes down, my site goes down. Adding a redis cache would be another point of failure. 

Thanks!
