### ISSUE TITLE
How i can connect to multiple redis servers.?

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#142]
How i can connect to multiple redis servers.?
I have given configuration as 

	string server="localhost";
	var cacheConfig = ConfigurationBuilder.BuildConfiguration(settings =>
	{
		settings
		.WithSystemRuntimeCacheHandle("inProcessCacheA").WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(15))
		.And
		.WithRedisConfiguration("redisCacheA", config =>
		{
			config.WithAllowAdmin()
				.WithDatabase(0)
				.WithEndpoint(server, 6380);
		})
		  .WithRedisConfiguration("redisCacheA1", config =>
		  {
			  config.WithAllowAdmin()
				  .WithDatabase(0)
				  .WithEndpoint(server, 6382);
		  }).
			WithRedisConfiguration("redisCacheA2", config =>
							{
								config.WithAllowAdmin()
									.WithDatabase(0)
									.WithEndpoint(server, 6381);
							})
		.WithMaxRetries(1000)
		.WithRetryTimeout(100)
		.WithRedisBackplane("redisCacheA", "redisCacheA")
		.WithRedisCacheHandle("redisCacheA", true); //.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(40))//.
		;
	});

	var cacheA = new BaseCacheManager<string>(cacheConfig);
     
to build a fault-tolerant redis cluster with sentinel.
My master is on the port 6380. slaves are on 6381 ,6382.
and sentinels are on 16380 ,16381 and 16382

when master goes down i am expecting that communication will continue to happen with my client.
but it thrown an exception. In the config files i see that master is changed in the voting process .
I am doing any thing wrong?

**Comment by MichaCo** [comment]
Each cache manager, or lets say, each redis cache handle can only use one redis configuration. So, adding multiple configurations doesn't really work that way.

Do have multiple endpoints defined for one redis configuration, just call `WithEndpoint` for each endpoint you have to add all of them, like 

	config.WithAllowAdmin()
		.WithDatabase(0)
		.WithEndpoint(server, 6380)
		.WithEndpoint(server, 6381)
		.WithEndpoint(server, 6382);

**Comment by vijay8059** [comment]
Does the replication happens between the servers? If the master  goes down, will it connect to newly elected master? or will it connect any of the available server?

**Comment by MichaCo** [comment]
That's totally unrelated to your question, but yes. 
All that fail over and reconnect stuff is handled by the Stackexchange.Redis client though.
