### ISSUE TITLE
DictionaryCacheHandle doesn't work in 1.0.0. Version on DEV branch does.

### ISSUE THREAD

**Issue by riazkarim** [MichaCo/CacheManager#143]
Does not expire items and doesn't fire OnRemoveByHandle

**Comment by MichaCo** [comment]
I cannot find any issues with the DictionaryCacheHandle in the released version 1.0.0 nor in current code (which is currently exactly the same as the released version btw ^^)

Just created a quick test, created a new console app, installed CacheManager.Core 1.0.0

    static void Main(string[] args)
    {

        var cache = CacheFactory.Build<int>(s => s.WithDictionaryHandle());

        cache.OnRemoveByHandle += (sender, evArgs) =>
        {
            Console.WriteLine(evArgs);
        };

        cache.Add("counter", 23);
        cache.Expire("counter", TimeSpan.FromSeconds(1));

        Console.ReadKey();
    }

Takes a few seconds and you'll get the event fired.

The check interval is 5 seconds, if you expect the items get evicted right away, that's not how things work. 
That being said, If you'd do a Get on the key right after it expired, it would trigger immediately and the Get would return Null.
 
If you have code to reproduce the behavior, I'll reopen the issue.
Thanks!
