### ISSUE TITLE
How to handle Stale data when Update fails in the cachemanager?

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#145]
I have a scenario want to know how the cache manager handle the updates.
1) If the update fails in the redis  due to n/w failure or some other reason. But it successfully saved to DB.
2) After the some time redis is up and client tries to get the value from redis it will be stale data right, 
How to handle these cases in the CacheManager? Is there any way already built?

TIA.

**Comment by MichaCo** [comment]
@vijay8059 

> ... But it successfully saved to DB

Do you mean the Redis "DB"? For example, your data was stored eventually but then we lost connection to Redis or something and the state of the data is unknown? Or what exactly do you mean?
Thanks,
m

**Comment by vijay8059** [comment]
Update to redis server fails. But updated to Database(ex: Sql server). After some time, redis server is UP and some client tries to get the that value from redis it will be stale data right
