### ISSUE TITLE
Cache Name doubts

### ISSUE THREAD

**Issue by hobojoe** [MichaCo/CacheManager#150]
Hi,

I've gone through the documentation but couldn't get one thing clear:

```
var _cache = CacheFactory.Build("getStartedCache", settings =>
        {
            settings.WithSystemRuntimeCacheHandle("handleName");
        });
```

If I have two cachemanager objects with the same cache config should I use different CacheNames?

What is the best approach if I have caches for multiple types of objects (string, int, CustomClass, etc.)? Should I create individual Cache objects for each type (and store each of them in a singleton - I don't use IOC) or should I create a single Cache object with type "object" and load everything in there?

Thanks in advance!

**Comment by MichaCo** [comment]
Hi @hobojoe, The name of the handle nor cache really matters for anything functional wise. The names will show up in logs though. So, if you want to identify which cache/layer logged an entry, it is useful to name them. But again, that's totally optional ;)

**Comment by hobojoe** [comment]
Ok.

And would I be loosing any functionality by using a single Cache Object with type "object" and load everything in there?

Thanks

**Comment by MichaCo** [comment]
that's up to you, too. You loose strongly typed code and might run into errors at runtime when you try to cast cached items to wrong things and such. But yeah, that's up to you ;)

**Comment by hobojoe** [comment]
Ok,

Thanks!
