### ISSUE TITLE
Can i use same ConnectionMultiplexer object for multiple ICacheManager objects

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#151]
Hi,
I want to create multiple IcacheManager objects in my application. Is it ok to same single ConnectionMultiplexer for multiple IcacheManager objects

           
            var options = new ConfigurationOptions { EndPoints = { { "localhost", 6378 } },
                ServiceName = "Redis-Test",
                AllowAdmin = true,
                KeepAlive = 180,
                ConnectRetry = 50,
                ConnectTimeout =5000,
                DefaultVersion = new Version(2, 8, 8),
                AbortOnConnectFail =false
                ,ConfigurationChannel = ""
               ,SyncTimeout = 3000
            };
			
			ConnectionMultiplexer multiplexer =ConnectionMultiplexer.Connect(options);
			

          ICacheManager<T>  _distributed = CacheFactory.Build<T>(
                s => s
                    .WithJsonSerializer()
                    .WithDictionaryHandle()
                        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(5))
                    .And
                    .WithRedisConfiguration("redisCh", multiplexer)
                      .WithMaxRetries(500)
                    .WithRetryTimeout(10000)
                    .WithRedisBackplane("redisCh", "redisCh")
                    .WithRedisCacheHandle("redisCh"));
        ICacheManager<T>      _distributed_copy = CacheFactory.Build<T>(
                s => s
                    .WithJsonSerializer()
                    .WithDictionaryHandle()
                        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(5))
                    .And
                    .WithRedisConfiguration("redisCh_copy", multiplexer)
                      .WithMaxRetries(500)
                    .WithRetryTimeout(10000)
                    .WithRedisBackplane("redisCh_copy", "redisCh_copy")
                    .WithRedisCacheHandle("redisCh_copy"));
					
		 ICacheManager<T> 			_distributed_copy_new = CacheFactory.Build<T>(
                s => s
                    .WithJsonSerializer()
                    .WithDictionaryHandle()
                        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(5))
                    .And
                    .WithRedisConfiguration("redisCh_copy_new", multiplexer)
                      .WithMaxRetries(500)
                    .WithRetryTimeout(10000)
                    .WithRedisBackplane("redisChredisCh_copy_new_copy", "redisCh_copy_new")
                    .WithRedisCacheHandle("redisCh_copy_new"));

**Comment by MichaCo** [comment]
Yes totally, it will use the same configuration anyways internally as it has the same connection string.

I' rewrite your code to 

``` 
ConnectionMultiplexer multiplexer = ConnectionMultiplexer.Connect(options);

var configuration = new ConfigurationBuilder()
    .WithJsonSerializer()
    .WithDictionaryHandle()
        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(5))
    .And
    .WithRedisConfiguration("redisCh", multiplexer)
    .WithMaxRetries(500)
    .WithRetryTimeout(10000)
    .WithRedisBackplane("redisCh", "redisCh")
    .WithRedisCacheHandle("redisCh"));

ICacheManager<T> _distributed = new BaseCacheManager<T>(configuration.Build());
ICacheManager<T> _distributed_copy = new BaseCacheManager<T>(configuration.Build());
ICacheManager<T> _distributed_copy_new = new BaseCacheManager<T>(configuration.Build());
```

**Comment by vijay8059** [comment]
Is gave channel names different, But in your code it's same in all instances. is there is no relevance for the channel names?

**Comment by MichaCo** [comment]
There is, sure, if you don't want to have cacheA sync with cacheB, use different channels. 
But if it is all in the same database/redis you can use the same channel, too.
Anyways, just remove the part with "WithCacheBackplane" from the "shared configuration" and move it into the initialization. As you see, I call ".Build" pretty late, until then, you can modify the parts which are different per cache manager instance.

**Comment by vijay8059** [comment]
The reason why i want to use different channels for different objects  is the changes that are made on one channel need to notified across to different severs on that channel. Don't want to get it notified to other objects

**Comment by MichaCo** [comment]
yeah makes sense, again, should totally work to have the same redis configuration for every CacheManager instance and also different backplane. The instances will still share one multiplexer ;)
