### ISSUE TITLE
Need an example on how to add CacheManager to a large solution...

### ISSUE THREAD

**Issue by freke1981SWE** [MichaCo/CacheManager#155]
Hello! I´ve started to replace an old InMemory cache class with CacheManager, due to the need of a more scaleable and multilevel cache. The solution contains several projects that need to have access to the same cache instance. So I´ve added a unity container and so on in the Global.asax

```

 var container = new UnityContainer();

            DependencyResolver.SetResolver(new UnityDependencyResolver(container));

            var cacheConfig = ConfigurationBuilder.BuildConfiguration(settings =>
            {
                settings
                    .WithSystemRuntimeCacheHandle("inprocess")
                    .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes((int)CacheExpires.In60Minutes))
                .And
                    .WithRedisBackplane("AzureRedis")
                    .WithRedisCacheHandle("AzureRedis", true)
                    .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes((int)CacheExpires.In60Minutes));
            });

            container.RegisterType(
                typeof(ICacheManager<object>),
                new ContainerControlledLifetimeManager(),
                new InjectionFactory(
                    (c, t, n) => CacheFactory.FromConfiguration(
                        t.GetGenericArguments()[0], cacheConfig)));
```
But how do I access the cache instance in the other projects? I´ve tried with this:

```
 [Dependency]
 protected ICacheManager<object> GlobalCacheManager { get; set; }
```
But it seems only to work in the main startup project, in the other projects the GlobalCacheManager gets null.

My second problem is how to serialize third party data models, so I can cache them to a Redis backplane. I´ve added these attributes to my own models:

```
    [Serializable]
    [JsonObject]
```
But some models contains nested models from third party nuget libs. Does anybody has idéas or good exampels, on how to inject the cache manager all over the place and how to serialize complex data models?

**Comment by MichaCo** [comment]
Those are two "problems" which not necessarily has anything todo with CacheManager ;)

The first one, you ask about standard DI patterns, If you want other libraries consume the cache, you'd have to inject e.g. `ICacheManager` to (usually) the ctor of the classes which should use it. 

let's say you have a class `MyEntityManager`

```cs
public class MyEntityManager 
{
   public MyEntityManager(ICacheManager<string> cache)
   {
       _cache = cache ?? throw new ArgumentNullException(nameof(cache));
   }
}
``` 
In DI you register open generic `ICacheManager<>`  or specifically typed one as you have.
(btw, you use the InjectionFactory to resolve the type to the generic argumet, but you register `typeof(ICacheManager<object>)` which will actually not work, or at least, if you only need object cache, you don't have to use injection factory).

Now, you also register `MyEntityManager` in DI, like, container.RegisterType<MyEntityManager>();

From now on DI should be able to new up MyEntityManager and inject ICacheManager.
That works for controllers, too as you already use DependencyResolver I guess.

Not sure what you are trying to achive with GlobalCacheManager property, where that thing sits and how others should access it. But that's probably not how your DI (should) works.

Regarding the serialization, which Serializer are you using, what errors do you get? 
If NewtonsoftJson cannot serialize your objects, they are probably not easily serializable, maybe have recursion and such? idk, you'd have to give more information about the error you are getting. But that would actually be a good question for Stackoverflow which has probably been answered a few 100 times already ;)

**Comment by freke1981SWE** [comment]
Hello, thanks for the fast reply. I understand that my problem has nothing to do with the CacheManager it self. I+m still struggling with my first "problem" on how to access the CacheManager from other controllers (managers).

I´ve added one manager to the container registration (the last row):

```
container.RegisterType(
                typeof(ICacheManager<>),
                new ContainerControlledLifetimeManager(),
                new InjectionFactory(
                (c, t, n) => CacheFactory.FromConfiguration(
                    t.GetGenericArguments()[0], cacheConfig)));

            container.RegisterType<ProductListManager>();
```
That manager is a basic class where I try by the cstor to inject the CacheManger:

```
 protected readonly ICacheManager _globalCacheManager;
        
        public ProductListManager(ICacheManager globalCacheManger)
        {
            _globalCacheManager = globalCacheManger;
        }
```
I some other controllers I instantiate the ProductListManager like this (to get a ProductManager with the CacheManager injected):

```
 IUnityContainer container = new UnityContainer();
var productMgr = container.Resolve<ProductListManager>();
```
But I always end up with the error:

An exception of type 'Microsoft.Practices.Unity.ResolutionFailedException' occurred in Microsoft.Practices.Unity.dll but was not handled in user code

Additional information: Resolution of the dependency failed, type = "Manager.ProductListManager", name = "(none)".

Exception occurred while: while resolving.

Exception is: InvalidOperationException - The current type, Manager.Caching.ICacheManager, is an interface and cannot be constructed. Are you missing a type mapping?

-----------------------------------------------

At the time of the exception, the container was:

  Resolving Manager.ProductListManager,(none)

  Resolving parameter "globalCacheManger" of constructor Manager.ProductListManager(Manager.Caching.ICacheManager globalCacheManger)

What is it that I´m getting wrong?

For the second "problem" I will test pn when I get the first "problem" to work. I really appreciate your help to get me in the right direction.

**Comment by ushenkodmitry** [comment]
Are you sure that you register cache manager  in the same container, from
which you are trying to resolve?

чт, 18 мая 2017 г., 23:36 freke1981SWE <notifications@github.com>:

**Comment by MichaCo** [comment]
@freke1981SWE Your container seems to try to resolve `Manager.Caching.ICacheManager` which is not the interface coming from this library. Are you injecting the wrong type or something?. 
You just seem to have some issues using Unity, again, that's more a StackOverflow question and not an Issue with CacheManager.  

Thanks,
m

**Comment by freke1981SWE** [comment]
Yes it seems, I will try SO out. Thanks.

Skickat från min iPhone
