### ISSUE TITLE
Setting Key name and Region name for Output/Response cache

### ISSUE THREAD

**Issue by vinogmca** [MichaCo/CacheManager#157]
Hi,

   We are using CacheManager.Web for our application Outputcacheprovider and we configured the output cache config section in web.config like below.
```
<!--Output Cache -->                 
  <cacheManager xmlns="http://cacheManager.michaco.net/schemas/cacheManagerCfg.xsd">
    <managers>
      <cache name="WebsiteCache" updateMode="Up" retryTimeout="500" maxRetries="3" enableStatistics="false" backplaneName="RedisCache" backplaneType="CacheManager.Redis.RedisCacheBackplane, CacheManager.StackExchange.Redis">
        <handle name="InProcess" ref="inMemoryHandle" />
        <handle name="RedisCache" ref="redisHandle" isBackplaneSource="true" />
      </cache>
    </managers>
    <cacheHandles>
      <handleDef id="inMemoryHandle" type="CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1, CacheManager.SystemRuntimeCaching" defaultExpirationMode="Sliding" defaultTimeout="2m" />
      <handleDef id="redisHandle" type="CacheManager.Redis.RedisCacheHandle`1, CacheManager.StackExchange.Redis" defaultExpirationMode="Sliding" defaultTimeout="1h" />
    </cacheHandles>
  </cacheManager>  
```
then under system.web configured the default provider as "CacheManagerOutputCacheProvider" and included the above config section under providers.
```
<system.web>
<caching>
    <outputCache defaultProvider="CacheManagerOutputCacheProvider">
        <providers>
          <add cacheName="WebsiteCache" name="CacheManagerOutputCacheProvider" type="CacheManager.Web.CacheManagerOutputCacheProvider, CacheManager.Web" />
        </providers>
      </outputCache>
    </caching>
  </system.web>
```

  How to add Region, key for Output/Response cache using cache manager.

  For ex, let's consider we have test.aspx and i am setting the below response cache.
```
   Response.Cache.SetCacheability(HttpCacheability.Server);
   Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(cacheMinutes));
   Response.Cache.SetValidUntilExpires(true);
   Response.Cache.VaryByParams["*"] = true;
```
   i do see the cache entry in REDIS, the key is something like below
  a2\test.aspx\HQNcacheminutesV15NjumpsearchV9110134NmaxresultsV50FCDE

   But i want to set my custom cache key with in particular region. How to achieve it? When i try to add like cachemanager.Add("mykey",Response,"myregion") in the test.aspx but i am getting serialization exception since HTTPRESPONSE can be serialized.

   Note: For output cache i just added the config section in web.config and no other code changes.

**Comment by MichaCo** [comment]
When using OutputCache, the cache is controlled by the ASP.NET framework. All keys are generated by the framework internally and you'll not have any control about that as far as I know. 
Even I don't really have much control in the output cache provider except that I basically just cache whatever the framework passes me in...

So, in short, there is no way you can modify how keys are generated for that output cache stuff.

If you want more control over what gets cached and how, I'd say don't use OutputCache at all and properly implement your site to use data/models which can be serialized and cached easily and implement caching for those parts of your application where it matters.

I don't think there is any other extensibility point in the ASP.NET framework where CacheManager could hook into or mark that whole thing more flexible. If I'm missing something, let me know ;)

**Comment by vinogmca** [comment]
Thanks a lot for the quick reply. How about writing CustomOutputCacheProvider which extends CacheManagerLibrary.CacheManagerOutputCacheProvider and invoke CacheManager.Add(), CacheManager.Remove() etc. 

Note: I didn't try just want to ask you if this work or did you or anybody tried this way

**Comment by MichaCo** [comment]
Sure, you can totally create your own custom output cache provider. Just copy&paste the existing one or extend it and do with it whatever you want ;)

**Comment by vinogmca** [comment]
Hopefully one final question, how come for Response cache , cache keys are getting added to REDIS.
  `Response.Cache.SetCacheability(HttpCacheability.Server);
   Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(cacheMinutes));
   Response.Cache.SetValidUntilExpires(true);
   Response.Cache.VaryByParams["*"] = true;`

**Comment by MichaCo** [comment]
@vinogmca not really sure if I understand your question, please clarify if the following doesn't answer it ;)

You configured a redis layer in your cache configuration, then, you configured the OutputCacheProvider to use that cache for caching page results.

The response/output cache feature of ASP.NET from then on handles the caching, CacheManager is just the storage/target where ASP.NET caches the page results.

So if ASP.NET decides to cache a page result, it will end up in Redis, and it uses a key determined by the ASP.NET framework.

**Comment by MichaCo** [comment]
My understand is that this is actually the same thing. You can control the cache behavior for both, server and client side caching using either `Response.Cache...` or the `[OutputCache]` attribute. 

If you configure it to cache on the `Server`, that means that the clients will receive a `no-cache` header and the server (your app / the ASP.NET framework) will cache the response data (in your case, throwing the data into Redis). 

You can also configure it to cache on the client, too/only, which makes a lot of sense for most pages to reduce load time and traffic and such..

**Comment by vinogmca** [comment]
OK GOT IT Thanks again :)

**Comment by MichaCo** [comment]
np ;)
