### ISSUE TITLE
Web Server CPU Bummer 

### ISSUE THREAD

**Issue by vinogmca** [MichaCo/CacheManager#158]
Hi,
   Today we deployed our REDIS caching system using your library to production. All the functionalities seems to be working fine but the web server CPU's took huge it. some insights

1] We are using In-memory(with 10m sliding expiration) and Redis as Backplane (1 hr sliding expiration)
2] Per second on an average 1K-2K cache keys will be loaded to redis (web crawlers use to hit the websites)
3]  We configured Redis Connectiontimeout as 5000ms and SyncTimeout as 5000 ms
4] We tried with both GzJsonCacheSerializer and JsonCacheSerializer
5] On Configuration stand point we have around 20 web servers with 12GB RAM with 8 CPU cores.

Unfortunately CPU utilization went up to 90% on all the web servers which forced us to rollback the entire changes(2 months effort 😞 ) .

Also we noticed that there was no memory problem on all the web servers.

We are suspecting  below things could be the problem

1) No of connections opened on REDIS by stackexchange.redis making the IIS unresponsive.

https://github.com/StackExchange/StackExchange.Redis/issues/266

2]Serialization/De-Serialization over the network causing CPU performance.

Anything we can do better here to overcome the problem?

**Comment by MichaCo** [comment]
Hey @vinogmca, sorry to hear you are having issues. I guess the best thing you can do is, profile your app. I cannot tell what is going on and why the CPU is at 90% all the time. You'd have to profile to figure out which parts are actually consuming the CPU and why. How much network traffic is going on and why.

If Json serialization should reallly be an issue, try another serializer and optimize your objects. How large are those models you are serializing? Must be insane if 2k keys/sec even tickles 8 Cores. If that's the case, maybe use Bond/Protobuf instead.

Try disable the backplane and first level cache to see if that's causing to much cross talk between the 20 servers. 

How many connections are registered on the Redis server? There should be only one connection per app instance (roughly).

**Comment by vinogmca** [comment]
Thanks @michaCo. 

Our Cache Manger class is a singleton instance and on constructor we are setting up the cache manager. So per instance it should be only one connection.

>  
static CacheManager()
        {
            #region CacheManager

            //Read the configuration from web.config/App.config
            var configuration = IsDistributedCacheEnabled
                               ? ConfigurationBuilder.LoadConfiguration("cacheManagerDistributed", "DistributedCache")
                               : ConfigurationBuilder.LoadConfiguration("cacheManagerInProcess", "InProcessCache");

             //pass the configuration object to cacheManager library and generate the new instance 
            cacheManager = CacheFactory.FromConfiguration<object>(configuration);          

            #endregion
        }
>

The below link forced us to think in REDIS connection standpoint.

http://www.nopcommerce.com/boards/t/40988/incorrect-redis-client-implementation-in-nop-370-causes-high-cpu-extraneous-threads-general-resource-consumption-slowed-response.aspx

**Comment by MichaCo** [comment]
I don't really see how the link has anything todo with it. And, from the code you posted I cannot tell anything about what your issues might be and there is nothing indicating a connection leak. (except that a static ctor doesn't make it a valid singleton, but ok)

If you want help, post numbers of how many connections you see on Redis. Add logging and post the log showing connections getting created on each request.

Add timings for how long serialization takes (maybe use benchmark.net to benchmark your code)..

**Comment by MichaCo** [comment]
@vinogmca I'm closing this now. If you still have issues and more details about it so I can actually help you, let me know
