### ISSUE TITLE
How to add Expiry for a key when we Use GetOrAdd.

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#166]
How to add Expiry for a key when we Use GetOrAdd.
Expecting Something similar to that of  AddOrUpdate(CacheItem<TCacheValue> addItem, Func<TCacheValue, TCacheValue> updateValue); wheere CacheItem<TCacheValue> addItem,  contains the ExpirationMode and TimeSpan,

**Comment by MichaCo** [comment]
See #152 and the PR. This will be coming soon
