### ISSUE TITLE
Feature request: be able to configure output cache from c# along with web.config

### ISSUE THREAD

**Issue by hermesramos** [MichaCo/CacheManager#169]
Please!

THanks

**Comment by MichaCo** [comment]
@hermesramos Is there any other way but web.config to define a custom `OutputCacheProvider`? If so, please let me know, couldn't find anything.
If you cannot configure it by code, I can also not inject anything to it by code. Which means, sorry, this is not possible.

**Comment by hermesramos** [comment]
You are right, from what I can tell, it is no possible.

Do you know if I it possible to set part of the CacheManger's configuration in c# (redis) and only the outputcache part in the web config?

Do know if I made myself clear.

Thanks in advance.

**Comment by hermesramos** [comment]
I think it may be possible. Check ScottGu's blog: https://weblogs.asp.net/scottgu/extensible-output-caching-with-asp-net-4-vs-2010-and-net-4-0-series

**Comment by hermesramos** [comment]
Do you know if it is possible to only set the outputcache in the web.config and set the remaining configuration in the c# (redis and stuff)?

As of know, because of the output cache, I am setting everying in the web.config.

Thanks in advance

**Comment by MichaCo** [comment]
Thats what I meant, there is no way to easily connect the two things, I have no control over when the outputcache thing gets initialized to inject a CacheManager instance which was created in your startup code. Would eventually be possible to do via static property or something, but that would be such a horrible design that I'm not willing to implement it ;)

**Comment by hermesramos** [comment]
Sorry for my poor english, I was not clear enough.

Can I combine configuration from C# , like bellow, with outputcache from web.config?

```
var cache = CacheFactory.Build<string>("myCacheName", settings =>
{
    settings
    .WithSystemRuntimeCacheHandle("handle1")
  .And
  .WithRedisCacheHandle("redis");
});

```
**with** 

```
<system.web>	    
  <caching>
    <outputCache defaultProvider="CacheManagerOutputCacheProvider">
      <providers>
        <add cacheName="myCacheName" name="CacheManagerOutputCacheProvider" type="CacheManager.Web.CacheManagerOutputCacheProvider, CacheManager.Web" />
      </providers>
    </outputCache>
  </caching>
</system.web>
```


will this work? I tried but could not make it work

**Comment by MichaCo** [comment]
As I said, nope, that's not going to work

**Comment by hermesramos** [comment]
Alright! Thank you very much for your time.
