### ISSUE TITLE
Max Memory Size that i can give for the Dictionary Handle 

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#170]
Max Memory Size that i can give for the Dictionary Handle

**Comment by MichaCo** [comment]
He @vijay8059, I assume you are asking for this as a feature request to add memory pressure based eviction to the dictionary cache handle?

This is not really easy to implement and even Microsoft remove their implementation lately from Microsoft.Extensions.Caching.Memory. I'm not planning to add that. But hey, if someone has a good idea how to do this, feel free to send a PR ;)

**Comment by vijay8059** [comment]
I need any in-memory cache handler so that i limit memory it's occupying, I don't cachehandler to bump my whole RAM. Is there any way i can do that?

**Comment by MichaCo** [comment]
As I mentioned in your other question, only System.Runtim.Caching supports that kind of mechanism (for in-memory) and you can configure it only via app/web.config. 

Redis and Memcache of course support that, too.
