### ISSUE TITLE
Bond serialization

### ISSUE THREAD

**Issue by hermesramos** [MichaCo/CacheManager#171]
Howdy!

Whenever I use any serialization from the Bond library, I get the following error:

**The method I am using: Cache.GetOrAdd**

**Stack trace** 
[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +65
   Bond.BondReflection.GetSchemaName(Type type) in S:\bondlab\nuget\bond\cs\src\core\BondReflection.cs:638
   Bond.BondReflection.GetSchemaFullName(Type type) in S:\bondlab\nuget\bond\cs\src\core\BondReflection.cs:664
   Bond.BondReflection.GetSchemaName(Type type) in S:\bondlab\nuget\bond\cs\src\core\BondReflection.cs:651
   Bond.BondReflection.GetSchemaFullName(Type type) in S:\bondlab\nuget\bond\cs\src\core\BondReflection.cs:664
   Bond.BondReflection.GetSchemaName(Type type) in S:\bondlab\nuget\bond\cs\src\core\BondReflection.cs:651
   Bond.Cache.GetMetadata(Type type) in S:\bondlab\nuget\bond\cs\src\core\Schema.cs:158
   Bond.Cache..ctor(Type type) in S:\bondlab\nuget\bond\cs\src\core\Schema.cs:69
   Bond.Schema`1..cctor() in S:\bondlab\nuget\bond\cs\src\core\Schema.cs:38

[TypeInitializationException: The type initializer for 'Bond.Schema`1' threw an exception.]
   Bond.Schema`1.get_RuntimeSchema() in S:\bondlab\nuget\bond\cs\src\core\Schema.cs:43

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +87
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture) +61
   System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index) +21
   Bond.Schema.GetRuntimeSchema(Type type) in S:\bondlab\nuget\bond\cs\src\core\Schema.cs:25
   lambda_method(Closure , Expression`1 , Type , Boolean ) +63
   Bond.Expressions.SerializerGeneratorFactory`2.Create(Expression`1 deferredSerialize, S schema, Boolean inlineNested) in S:\bondlab\nuget\bond\cs\src\core\expressions\SerializerGeneratorFactory.cs:16
   Bond.SerializerHelper..ctor(ObjectParser parser, Type type, Boolean inlineNested) in S:\bondlab\nuget\bond\cs\src\core\Serializer.cs:140

**Comment by MichaCo** [comment]
That's the kind of exception you get if your objects cannot be serialized by Bond because it cannot create a schema for it. Usually, because of missing/incorrect attributes. 

But I guess you figured that out already ;)
