### ISSUE TITLE
Provide ability to decorate or extend ICacheManager

### ISSUE THREAD

**Issue by erizzo** [MichaCo/CacheManager#176]
I want to add some behavior (and state) to the out-of-the-box ICacheManager implementation. Normally I'd just write my own class that implements the interface, has a private field of the interface type that's passed in to the constructor, and implement the interface methods as calls to that field.
The problem is that ICacheManager has 60+ methods, making it impractical to implement. My second thought was to extend BaseCacheManager, but that class is sealed.

So I need a lightweight way to decorate the cache manager, still exposing all (well, most) of its methods. Simplest suggestion I can think of is to un-seal BaseCacheManager, but I wonder why it was sealed in the first place - maybe there's more than meets the eye in that decision.

**Comment by MichaCo** [comment]
Hi @erizzo,
I will have a look why the BaseCacheManager is sealed, not really sure why this is as I usually don't like to have any sealed classes in public APIs if possible ^^. I'll probably remove it

**Comment by MichaCo** [comment]
fixed in release 1.1.2
