### ISSUE TITLE
Unity Dependency Injection with Unity MVC

### ISSUE THREAD

**Issue by pgardella** [MichaCo/CacheManager#178]
Good afternoon!

This may be a problem with my knowledge of DI at this point. If so, my apologies!

This is with Cache Manager 1.1.1

I'm following your example of the [Single Page ToDo](https://github.com/MichaCo/MichaCo.Websites/tree/67ccfed43095c3586cf973ede20f41e72ebd380d/cachemanager-todo.azurewebsites.net/Website) except with Unity MVC insead of Unity WebAPI.

In Global.asax.cs during app initialization (Application_Start), I create the IUnityContainer and register the Cache Manager instance:

 ```
var container = new UnityContainer();
DependencyResolver.SetResolver(new UnityDependencyResolver(container));
var cacheConfig = ConfigurationBuilder.BuildConfiguration(settings =>
       {
                settings
                    .WithSystemRuntimeCacheHandle(false)
                    .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromSeconds(3600));
            });

            container.RegisterType(
                typeof(ICacheManager<>),
                new ContainerControlledLifetimeManager(),
                new InjectionFactory(
                    (c, t, n) => CacheFactory.FromConfiguration(
                        t.GetGenericArguments()[0], cacheConfig)));
```

Then in the helper class (which is where I use the cache), I add a property with the Dependency attribute on:

```        
[Dependency]
public ICacheManager<List<Term>> AllTermCache { get; set; }
```

In my method, I get a Null Reference Exception anytime I try to use AllTermCache, whehter I'm PUTing or checking if it exists:

```
List<Term> testvar = new List<Term>();

AllTermCache.Put("Test", testvar);
```

or 

```
if (AllTermCache.Exists("Terms")) {
    _log.Debug("Terms found in cache. Returning cached values.");
    return (List<Term>)AllTermCache.Get("Terms");
 }
```

What did I miss in the example code on GitHub?

**Comment by MichaCo** [comment]
Yeah this seems to have nothing todo with CacheManager.
Anyways, did you also change the ToDoController to extend from `Controller` (MVC) instead of `ApiController` (API)?

**Comment by pgardella** [comment]
Thanks. Found the problem, which should have been obvious. If you are using the MVC Unity container, you need to put the caches somewhere in the MVC code.

I had it in a separate helper class, outside the Controller.
