### ISSUE TITLE
Is there any documentation on concurrency scenarios this library handles

### ISSUE THREAD

**Issue by srivathsah** [MichaCo/CacheManager#181]
Hi, 
Thanks for a great product, is there any part of the documentation that deals with the concurrency aspects of the cache, like thread safety, atomicity .. both in-memory and distributed. If there is no such doc, could you please just brief here. I need to know what kind of operations I need to consider myself that the library does not provide out of box

**Comment by MichaCo** [comment]
The library is thread safe in general. Of course, this doesn't handle concurrent modifications. 
If you care about concurrency with a distributed cache, you can make use of the `Update` method which is documented with some examples here: http://cachemanager.michaco.net/documentation/CacheManagerUpdateOperations
