### ISSUE TITLE
Different levels of caching

### ISSUE THREAD

**Issue by srivathsah** [MichaCo/CacheManager#182]
Is there any possibility of configuring a multi-layered cache out-of-the-box when we use both in-memory and Redis cache. ie for eg: if we want to find an item, first we do so in the in-memory cache, if not found, then fetch from Redis

**Comment by MichaCo** [comment]
That's the default behavior of CacheManager if multiple layers are configured. The order in which you configure the cache handles matters. First should be in-memory, second => redis.
