### ISSUE TITLE
Redis backPlate doesn't work when configured from config file

### ISSUE THREAD

**Issue by BatsIhor** [MichaCo/CacheManager#19]
Redis backPlate doesn't work when configured from config file.
I am using following configuration in web.config:

```xml
 <configSections>
    <section name="cacheManager" type="CacheManager.Core.Configuration.CacheManagerSection, CacheManager.Core" />
    <section name="cacheManager.Redis" type="CacheManager.Redis.RedisConfigurationSection, CacheManager.StackExchange.Redis" />
  </configSections>
  <cacheManager.Redis>
    <connections>
      <connection id="redis1" database="0" >
        <endpoints>
          <endpoint host="127.0.0.1" port="6379" />
        </endpoints>
      </connection>
    </connections>
  </cacheManager.Redis>
 
  <cacheManager xmlns="http://tempuri.org/CacheManagerCfg.xsd">
    <managers>
      <cache name="redisWithBackPlate" enableStatistics="false" backPlateName="redis1" backPlateType="CacheManager.StackExchange.Redis.RedisCacheBackPlate, CacheManager.StackExchange.Redis">
        <handle name="default" ref="runtimeHandle" />
        <handle name="redis1" ref="redisHandle" expirationMode="None" isBackPlateSource="true" />
      </cache>      
    </managers>
    <cacheHandles>
      <handleDef  id="runtimeHandle" type="CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1, CacheManager.SystemRuntimeCaching" defaultExpirationMode="Sliding" defaultTimeout="5m"/>
      <handleDef  id="redisHandle"  type="CacheManager.Redis.RedisCacheHandle`1, CacheManager.StackExchange.Redis" defaultExpirationMode="Sliding" defaultTimeout="5m" />
    </cacheHandles>
  </cacheManager>
```

but after running two instances of application I see that variable Configuration.BackPlateType is set to null and backPlate doesn't work.

at the same time with following configuration in code it works perfectly. 

```cs
  ICacheManager<object> cache = CacheFactory.Build<object>("myCache", settings =>
            {
                settings
                    .WithSystemRuntimeCacheHandle("inProcessCache")
                    .And
                    .WithRedisConfiguration("redis", config =>
                    {
                        config.WithAllowAdmin()
                            .WithDatabase(0)
                            .WithEndpoint("localhost", 6379);
                    })
                    .WithMaxRetries(1000)
                    .WithRetryTimeout(100)
                    .WithRedisBackPlate("redis")
                    .WithRedisCacheHandle("redis", true);
            });
```

Looks like a bug in config file parsing. 

Thanks 
Ihor

**Comment by MichaCo** [comment]
Yup this seems to be a bug, thanks for reporting ;)

**Comment by MichaCo** [comment]
I figured that this is actually not a bug in code, the configuration was wrong.
The backPlateType must be defined like this: 

    backPlateType="CacheManager.Redis.RedisCacheBackPlate, CacheManager.StackExchange.Redis"

The namespace of the type had `CacheManager.StackExchange.Redis.RedisCacheBackPlate` in your case. Change it to `CacheManager.Redis.RedisCacheBackPlate` and it should work.

I added some unit tests to read and use the backplate from configuration, I also fixed the examples in the documentation, so in fact it was a bug in the documentation ;)

**Comment by BatsIhor** [comment]
I need to use configuration from config file as it will be configured for different environments. 
Thanks a lot, really good job!

**Comment by olaj** [comment]
Just for people like me that are running in to this post while googling. It doesn't seem to be "backPlate" but "backPlane" nowdays :)

**Comment by manoharsingh2110** [comment]
I have been trying to use the same configuration code with the edits suggested.

But, i get this exception : Unrecognized attribute 'backPlaneName'. Note that attribute names are case-sensitive.

If I remove the backPlane attributes, it works fine. What can I be doing wrong here?

`  <cacheManager xmlns="http://cachemanager.net/schemas/CacheManagerCfg.xsd">
    <managers>
      <cache name="cacheName" enableStatistics="false" backPlaneName="redis1" backPlaneType="CacheManager.Redis.RedisCacheBackPlate, CacheManager.StackExchange.Redis">
        <handle name="default" ref="runtimeHandle" />
        <handle name="redis1" ref="redisHandle" expirationMode="None" isBackPlaneSource="true" />
      </cache>
    </managers>
    <cacheHandles>
      <handleDef  id="runtimeHandle" type="CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1`, CacheManager.SystemRuntimeCaching" defaultExpirationMode="Sliding" defaultTimeout="5m"/>
      <handleDef  id="redisHandle"  type="CacheManager.Redis.RedisCacheHandle`1`, CacheManager.StackExchange.Redis" defaultExpirationMode="Sliding" defaultTimeout="5m" />
    </cacheHandles>
  </cacheManager>`

**Comment by MichaCo** [comment]
looks like it is `backplaneName` ?

https://github.com/MichaCo/CacheManager/blob/dev/test/CacheManager.Tests/Configuration/configuration.valid.allFeatures.config#L47

Sorry ;)

**Comment by manoharsingh2110** [comment]
Thank you! That helped. :)
