### ISSUE TITLE
Only add, put, update to a single handle when multiple handles are configured

### ISSUE THREAD

**Issue by alkesos84** [MichaCo/CacheManager#190]
I have the following use case with CacheManager:

1. A backend service with Redis handle only
2. Multiple web clients with Redis handle and in-proc handle

The backend service updates L1 data (data that is often requested) every 10 minutes in Redis (the item has no expiration as I don't want the items to expire leaving the web clients with no data in the cache). 

The scenario I am trying to find a solution to is:

1. The web client asks for L1 data and therefor first checks the in-proc handle. If not found in-proc it will check Redis handle (where it always should be available thanks to the backend service).
2. If the data is found in Redis handle then cache the data in the in-proc handler for 15 minutes (don't cache in Redis handler as L1 data should never have any expiration in Redis).
3. If the data is NOT found in Redis handler (should not happen) then fetch from SQL-database and cache in Redis handler and in-proc for 15 minutes

To my understanding it is not possible to have separate cache operations per handle. I have read the api and can't see any overloads to the Add(), Update() or Put() methods that makes this possible. Am I missing something?

1. Works out of the box with CacheManager.
2. Is this possible with CacheManager? I want to .Put() only to in-proc handle and don't touch the Redis handle.
3. This should be possible with CacheManager with a simple .Put()

I know that you can define the Expiration per handle in the configuration but this is not flexible enough for my use case.

**Comment by alkesos84** [comment]
After some research it seems that the ICacheManager interface exposes a property called: CacheHandles.

With this property you could do: 

`_cache.CacheHandles.First().Put("key", "value") `

Where the first handle is the in-proc handle in my case.

It seems to work just fine for my use case. Are you supposed to use this property like this?

**Comment by MichaCo** [comment]
CacheManager does that for you per default if you have 2 layers of cache for example.
On `Get` if the key was found in Redis but not in-memory, it will be added to the in-memory handle and the next `Get` will get it from there...

Just set your expiration per cache handle and your scenario should just work I guess

**Comment by alkesos84** [comment]
Thanks for the reply. You are correct that the Get-operation works out of the box for my use case.

However, I believe, setting the expiration per cache handle is not flexible enough for me. To my understanding you set the expiration once per handle during configuration and then you can override this by using expiration for the items that you cache. In order to achieve the behaviour 2. above I would have to configure my Redis handle to have Expiration.None and In-proc handle 15 minutes and then it would work I guess. 

The expiration configuration for in-proc handle would be:

`.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(15))`

And the expiration configuration for Redis handle would be:

`.WithExpiration(ExpirationMode.None, TimeSpan.Zero)`

But what if I have another set of data that doesn't change that often and I want to cache it the same way but with an expiration of 60 minutes in the in-proc handle and with no expiration in the Redis handle? If I specify an expiration of 60 minutes for the cache item it will override the expiration set on the handles and both in-proc and Redis will now have it cached for 60 minutes. To me it seems I am now stuck with caching for 15 minutes in-proc (because this is set during configuration) if I don't want to cache with expiration in Redis at the same time.

**Comment by MichaCo** [comment]
Yes, that's what I meant with setting the expiration per cache handle.

If you have another type/object to cache with different expiration settings, just create another CacheManager/Configuration for that one ;)
You are not limited to just one CacheManager instance

**Comment by alkesos84** [comment]
Thank you, that makes sense :) I don't know why I was under the impression that you were limited to a single CacheManager. You may close this issue :)
