### ISSUE TITLE
"Something is wrong with the Lua scripts. Seem to be not loaded."

### ISSUE THREAD

**Issue by JingLi-kooboo** [MichaCo/CacheManager#191]
We got some exception log with "Something is wrong with the Lua scripts. Seem to be not loaded.", I find it on CacheManager.StackExchange.Redis/RedisCacheHandle.cs line:993, but I don't sure what would happen to it.

**Comment by MichaCo** [comment]
That might happen in some cases if Redis nodes fail over or restart and the scripts where not loaded yet. 
Or, the server doesn't support Lua I guess.
Does it happen on every call or just from time to time?

**Comment by JingLi-kooboo** [comment]
It happens only occasionally, the version is 0.9.2. I updated it to the latest version, I hope it won't happen again.

**Comment by MichaCo** [comment]
Closing this for now
