### ISSUE TITLE
Best way to handle multiple CacheManagers

### ISSUE THREAD

**Issue by themakshter** [MichaCo/CacheManager#195]
I want to create multiple instances of CacheManagers. Each of them will be for caching a specific data type and hence have their own custom config, regions and key generation logic. I plan on creating single instances of these and using each of these instances where necessary. I was just wondering if that works from a design point of you as you would know best regarding the library. I plan on using a Factory pattern for creating these and maybe try to see how I can create DIs with the help of the factory at App start up. Does that make sense to you or is there wheel re-invention going on here by me?

**Comment by MichaCo** [comment]
Yes you can totally have different configurations for different types and have as many CacheManager singletons in your app as you want.
Just keep in mind that in-memory caches are **not** shared while Redis or other distributed caches will be.

See https://github.com/MichaCo/CacheManager/blob/dev/samples/AspnetCore.WebApp/Startup.cs#L38 how to achieve that with the MS DI container.
You can do the same with any Factory or DI framework.

In [line 47](https://github.com/MichaCo/CacheManager/blob/dev/samples/AspnetCore.WebApp/Startup.cs#L47), I'm adding the open generic definition `services.AddCacheManager();` (which is a shortcut for `collection.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));`). This will always use the singleton CacheManagerConfiguration added earlier in line 38.

To add a different configuration for one type, see line 41 and 44.

Hope that helps

**Comment by themakshter** [comment]
Thank you for taking the time to reply to me, I am grateful for your help. 

What you have said makes sense, but I am unsure how to apply to my particular application. We still haven't started using a `Startup.cs` file and have most of our set up in the `Global.asax`. Moreover, a lot of places where we might want to use a cache are static methods within multiple classes so it seems impractical to add a private `ICache` to those classes.

Just one more thing to clarify: I can have different singletons of the same type as well right? As long as they have different configurations (one of them will at least have a different config name)

**Comment by MichaCo** [comment]
The examples are for the new ASP.NET Core stuff, it doesn't matter though as the concept should be the same. You just might have to write a little bit more code yourself and choose a DI framework or build your own factory. That's all totally up to you ^^

> Just one more thing to clarify: I can have different singletons of the same type as well right

You have to handle the singletons, so it is totally up to you how many you have and of what type. From CacheManager perspective, there is no limitation or so.

**Comment by themakshter** [comment]
yeah, that is what I am steeling myself to do. I have some ideas to do so, but I also wanted to make sure I don't end up doing the exact same thing CacheManager might already provide me with the capability of doing. Thank you for being so helpful, I hope you do not mind the numerous clarification requests.
