### ISSUE TITLE
Should I cache json, Bson or JObject in the ICacheManager?

### ISSUE THREAD

**Issue by gautelo** [MichaCo/CacheManager#196]
I have some [Json.NET](https://www.newtonsoft.com/json) `JObjects` which I need to cache, and I wonder what best practice is when caching such data in `CacheManager`?

I'm concerned with
1. Using a reasonably small amount of memory in the cache.
2. Not unnecessarily serialize to avoid useless processing.

If I cache the json `string` I need to parse it every time I read the cache.

If I cache the `JObject` I don't know how it will be serialized to the cache. Probably as a non-compact binary array. But I won't have to do anything to it after retrieving it.

That's why I'm considering that perhaps it will serialize `Bson` better, or maybe that's going to simply add another layer of serialization? After all, I'll have to convert the `Bson` to `JObject` when reading the cache, much like if I were to cache the json string.

PS: I posted this [question](https://stackoverflow.com/questions/46545486/should-i-cache-json-bson-or-jobject-in-the-icachemanager) to SO a while ago, but no answer has been forthcoming, so I figured I'd try my luck here.

**Comment by MichaCo** [comment]
It depends, are you going to use distributed cache? If so, yeah you have to care about serialization and de-serialization. In that case, you can either let CacheManager handle serialization or you cache the string and care about it yourself.

If you use in-memory cache only, you can cache any kind of objects and no extra serialization will be done to put or read from cache, obviously, because it is in memory... ;)

**Comment by gautelo** [comment]
We're using both local and distributed cache. With that in mind, how do you think I should proceed?

When you say "let CacheManager handle serialization" what do you mean by that? Is that when I simply dump the JObject straight into the cache?

Is there a way to control how CacheManager serializes things? I don't see any hooks for attaching a custom serializer or some such.

Basically to ensure optimal serialization of any custom type, it must be a `SerializableAttribute` type or are you using some other mechanism? I'm asking, cause I'm used to Json.NET and MongoDB which both require custom serializers for some things.

**Comment by gautelo** [comment]
So, after a bit of testing it seems the whole placing the JObject into the cache is off the table. Attempting to cache it causes an exception to be thrown saying "Type 'Newtonsoft.Json.Linq.JObject' in Assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' is not marked as serializable."

Ok. That wasn't very surprising, as I already expected SerializableAttribute to be the serialization mechanism.

Considering the Bson intermediary: I don't think it's useful. I didn't realize what it was for. It's for when your CLR objects are base64encoded due to protocol requirements. As I don't see any such requirements within CacheManager, nor do I have them in my application, the option is off the table.

That leaves only one option, as far as I can tell, and that is caching the json as a string, and parsing it after reading the cache.

Does your analysis coincide with mine?

**Comment by MichaCo** [comment]
Yeah Jobject will not "just" work as it is an intermediate from Newtonsoft JSON

There is a CacheManager.Serialization.Json nuget package which uses Newtonsoft JSON.... you can install and use that...
Not sure what the best is as I never worked with the linq objects and caching directly. Usually you'd create Pocos and cache those.
But it should be possible to get that working. Let me know how it goes, otherwise I'll give it a try later when I find some time...

**Comment by gautelo** [comment]
If I understand correctly, the CacheManager.Serialization.Json will swap out the default binary serializer with a json based serializer which is probably quite a bit less efficient in general.

I haven't tried it, cause even if it would allow me to cache JObject directly, I'm not sure I believe it's worth it. I'd have to do some perf tests, but since caching the json string and parsing on retrieval seems to work great, I think I'll conclude that this is, for our scenario, the best way.

Thanks for your help, @MichaCo!

**Comment by MichaCo** [comment]
@gautelo just to be clear, binary serialization has usually the worst performance. If you are interested in numbers, here you have them: https://github.com/MichaCo/CacheManager/blob/dev/test/CacheManager.Benchmarks/BenchmarkDotNet.Artifacts/results/SerializationBenchmark-report-github.md

**Comment by gautelo** [comment]
@MichaCo Interresting. Though I don't think it's fair to compare the BinarySerializer to the JsonSerializer since I expect the Binary output to be more compact than the Json output. So, comparing BinarySerializer to the JsonGzSerializer seems more reasonable, and they're equally performant.

I'm not sure my compactness argument holds, of course, as I haven't compared the actual outputs. (I probably should.) I'm a bit weary, since the binary serializer might put a lot of metadata for types into the output which could bloat it.

That said, if bandwidth and memory use is not the bottleneck, then in terms of the serialization itself, I'd agree with you.

I just feel there is more to performance than the serialization operation itself, and compactness is one of them.
