### ISSUE TITLE
about ioc registerType

### ISSUE THREAD

**Issue by capqueen** [MichaCo/CacheManager#20]
```
UnityContainer container = new UnityContainer();
 container.RegisterType<ICacheManager<A>>(
new ContainerControlledLifetimeManager(),
new InjectionFactory((c) => CacheFactory.FromConfiguration<A>("myCache")));
```
I has many class A、B、C...so when init IOC by code above, there will be many same code. 
How can I simply register multiple types to IOC container?

**Comment by MichaCo** [comment]
Hi @capqueen 
Great question. Unfortunately, for now, you'd have to register all types of cache manager you might need.

But we can improve that. InjectionFactory has an overload which takes a func which provides also the target type which should be created. With that, we could create the needed type. Like that:

    container.RegisterType(typeof(ICacheManager<>), new InjectionFactory((c, t, n) => CreateManager(t)));

The CreateManager method should look similar to this:

    private static object CreateManager(Type type)
    {
        var genericArgs = type.GetGenericArguments();
        if (!type.IsGenericType || genericArgs.Length != 1)
        {
            throw new InvalidOperationException("nope...");
        }

        var targetType = genericArgs.First();

        return CacheFactory.Build(targetType, "myCache", cfg => cfg.WithSystemRuntimeCacheHandle("h1"));
         
        // or   
        // return CacheFactory.FromConfiguration(targetType, "myCache", ConfigurationBuilder.LoadConfiguration("myCfg"));
    }

The problem now is that `CacheFactory` does not provide overloads which take the type. Instead `CacheFactory` has generic methods for that. It is a little bit a hassle to call those generic methods via reflection if you have to work with `Type` (but it is doable)

I might add those overloads if I find some time, or if someone else wants to do it, would be fine, too.

**Comment by capqueen** [comment]
Thanks a lot, I'll try

**Comment by MichaCo** [comment]
I just checked in some changes to `CacheFactory` and released and update on nuget.org. 
Now you can use it with unity like this for example:

            UnityContainer container = new UnityContainer();
            container.RegisterType(typeof(ICacheManager<>),
                new ContainerControlledLifetimeManager(),
                new InjectionFactory((c, t, n) => 
                    CacheFactory.Build(
                        t.GetGenericArguments()[0], 
                        "name", 
                        cfg => cfg.WithSystemRuntimeCacheHandle("h1"))));

We have to pass `t.GetGenericArguments()[0],` as the type and not just `t`. Why?
Because the type passed in to the `Func` is `ICacheManager<T>` and we have to pass only the `T´ to the `Build` or `FromConfiguration` method.

Instead of `CacheFactory.Build` in the example above you can of course also use `CacheFactory.FromConfiguration(...)`.

**Comment by capqueen** [comment]
wow, great work~ I have a question, why not cachemanager have api like ICacheManager.Add<T> / Set<T> ...? is it about some design reason?
