### ISSUE TITLE
Missing async support

### ISSUE THREAD

**Issue by xplatsolutions** [MichaCo/CacheManager#209]
Great job!

I started using until I hit a roadblock, I was using a library that has async support, for example I want to do the below using memory caching.

var item = CacheManager.GetOrAdd(
                cacheKey,
                async () => await FetchFromDatabaseAsync(query).ConfigureAwait(false)
);

So basically I need a Task<T> and Task<CacheItem<T>> for the Func<string, T> and Func<string, CacheItem<T>> delegate parameters.

Is there a workaround I'm missing?

**Comment by xplatsolutions** [comment]
I believe a workaround like this would suffice but out of the box support would be great since everything is async today.

```
public static async Task<T> GetOrAddAsync<T>(
            this ICacheManager<T> cacheManager, 
            string key, 
            Func<string, Task<T>> valueFactory)
        {
            var result = default(T);

            if (cacheManager.Exists(key))
            {
                result = cacheManager.Get<T>(key);
            }
            else
            {
                result = await valueFactory(key).ConfigureAwait(false);
                cacheManager.Add(key, result);
            }

            return result;
        }

        public static async Task<T> GetOrAddAsync<T>(
            this ICacheManager<T> cacheManager, 
            string key, 
            Func<string, Task<T>> valueFactory, 
            ExpirationMode expirationMode,
            TimeSpan timeout)
        {
            var result = default(T);

            if (cacheManager.Exists(key))
            {
                result = cacheManager.Get<T>(key);
            }
            else
            {
                result = await valueFactory(key).ConfigureAwait(false);
                cacheManager.Add(new CacheItem<T>(key, result, expirationMode, timeout));
            }

            return result;
        }
```

**Comment by MichaCo** [comment]
see #184

**Comment by xplatsolutions** [comment]
.Wait for a Task is the worst you can do to introduce deadlocks in your application.

I understand the async I/O and that is my point, I have async IO operations to fetch the value and add to the cache.

**Comment by rahulbpatel** [comment]
+1
