### ISSUE TITLE
GetStatistic() question

### ISSUE THREAD

**Issue by AccessViolator** [MichaCo/CacheManager#215]
My understanding is that GetStatistic() will only show stats for particular TCacheValue. If so then is there a way to collect stats across all cached types (apart from injecting ICacheManagers for all cached types)?

**Comment by MichaCo** [comment]
Stats are collected per instance of CacheManager. If you have multiple instances, then no there is no way to make it collect stats for all of those. You'd have to do that yourself.

**Comment by AccessViolator** [comment]
Per instance of CacheManager and not per handle of CacheManager (because GetStatistic() is accessible through a handle, not through CacheManager)?

**Comment by MichaCo** [comment]
Yeah it is per handle per instance.
You can find an [example in the api docs](http://cachemanager.michaco.net/documentation/api/CacheManager.Core.Internal.CacheStats-1.html#CacheManager_Core_Internal_CacheStats_1_GetStatistic_CacheManager_Core_Internal_CacheStatsCounterType_) how to access it.

It is probably not the most friendly implementation right now, but it was for testing and playing with that kind feature in the first place anyways and it never really evolved further ;)

**Comment by AccessViolator** [comment]
Thanks. The example seems
1. Invalid - there's no non-generic FromConfiguration method that takes first param of type string
2. Kinda misleading - according to docs FromConfiguraion creates a new instance of cache manager, so threre's no point in getting stats on it :)

**Comment by MichaCo** [comment]
?? That's not the point of the answer dude. Ofc FromConfiguration creates a new instance. That's just an example of iterating over cache handles and getting stats.
The overload used in the example doesn't exist anymore, yes, but again...

**Comment by AccessViolator** [comment]
Sorry if I offended you or something, but docs could be better - in my book examples are supposed to work :)

**Comment by MichaCo** [comment]
No worries ;)
The documentation/examples might just be a little bit outdated. There was an overload with just a string in an earlier version, the API just changed slightly.
