### ISSUE TITLE
OnRemoveByHandle not working with Redis

### ISSUE THREAD

**Issue by arrkaye** [MichaCo/CacheManager#224]
Hi,

I've configured my cache as below, but am not getting the OnRemoveByHandle called.

`
Configuration = new ConfigurationBuilder()
				.WithJsonSerializer()
				.WithRedisConfiguration("redis", c =>
				{
					var connectionString = cp.DataOptions.Cache.Split(":");
					c
						.WithAllowAdmin()
						.EnableKeyspaceEvents()
						.WithEndpoint(connectionString[0], int.Parse(connectionString[1]));
				})
				.WithRedisBackplane("redis")
				.WithRedisCacheHandle("redis", true).Build();
`

Cache is being created like so:

` 
_cache = CacheFactory.FromConfiguration<T>(Configuration);
_cache.OnRemoveByHandle += OnExpiry;
`
I see the item being added and expired from the cache in RedisDesktopManager.

Any idea what I could be doing wrong?

**Comment by MichaCo** [comment]
Do you have key space events with the required settings enabled on the Redis server?

**Comment by arrkaye** [comment]
What value does that need to be set to in the redis.conf?

**Comment by MichaCo** [comment]
https://github.com/MichaCo/CacheManager/blob/dev/src/CacheManager.StackExchange.Redis/RedisConfigurationBuilderExtensions.cs#L44

**Comment by arrkaye** [comment]
Figured it out. Thanks!

**Comment by MichaCo** [comment]
Great ;)
