### ISSUE TITLE
How to get CacheManager working with ASP.NET Web API + NInject

### ISSUE THREAD

**Issue by wujitouch** [MichaCo/CacheManager#23]
The System.Runtime.Caching.MemoryCache.Default is not cleared until appdomain shutdown. The memory cache in CacheManager is cleared on every new http request. I'm using it in an asp.net mvc web api controller.

Looking at the code, it's suppose to use MemoryCache.Default if the handle name is empty or the default of "default". It doesn't seem to be doing that. I think it's creating a new instance of MemoryCache each time.

line 50 here
https://github.com/MichaCo/CacheManager/blob/master/src/CacheManager.SystemRuntimeCaching/MemoryCacheHandle%601.cs

This is my configuration section:

	<cacheManager xmlns="http://tempuri.org/CacheManagerCfg.xsd">
		<managers>
			<cache name="defaultCache" updateMode="Up" enableStatistics="false" enablePerformanceCounters="false">
				<handle name="default" ref="systemRuntimeHandle" expirationMode="Absolute" timeout="5m"/>
			</cache>
		</managers>
		<cacheHandles>
			<handleDef  id="systemRuntimeHandle" type="CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1, CacheManager.SystemRuntimeCaching"
			  defaultExpirationMode="Sliding" defaultTimeout="5m"/>
		</cacheHandles>
	</cacheManager>

Sample code showing that they work differently:

	string key = "key";
	var stringCache = CacheFactory.FromConfiguration<string>("defaultCache");
	var myValue = stringCache.Get(key);
	if (myValue == null)
	{
		stringCache.Add(thingerCacheKey, "test");
	}

	key = "key2";
	myValue = MemoryCache.Default.Get(key) as string;
	if (myValue == null)
	{
		var policy = new CacheItemPolicy
		{
			SlidingExpiration = TimeSpan.FromMinutes(5)
		};
		MemoryCache.Default.Add(key, "test", policy);
	}

**Comment by MichaCo** [comment]
Your example will not work. CacheManager adds a randomly generated string to the key to mark the instance of cache manager, so that e.g. two instances of cache manager using the same memory cache instance do not affect each other...

the key you specify might be `"key"`, the actual key stored is something like `"e904fdb8-2c79-4b24-8e78-29470f4e6796:key"`

CacheManager **does** use `MemoryCache.Default` if the cache name is "default". See https://github.com/MichaCo/CacheManager/blob/master/src/CacheManager.SystemRuntimeCaching/MemoryCacheHandle%601.cs#L44, the if statement...

Here is a pretty simple example to show that:

            var cache = CacheFactory.FromConfiguration<string>("defaultCache");
            cache.Put("key", "value");
            var aC = System.Runtime.Caching.MemoryCache.Default.GetCount(); // == 2 
            var a = cache.Get("key");   // != null
            cache.Remove("key");
            var bC = System.Runtime.Caching.MemoryCache.Default.GetCount(); // == 1
            var b = cache.Get("key");   // == null

Regarding your comment:

> The memory cache in CacheManager is cleared on every new http request. I'm using it in an asp.net mvc web api controller

This is most likely because you are instantiating a new `CacheManager` for every request. Use a singleton or better use DI and let the DI Framework handle the lifetime...

Let me know if that doesn't help ;)

**Comment by wujitouch** [comment]
Thanks, that clears things up. I'm not sure how to fix my problem, however, because I suspected it had something to do with new instances and I couldn't get Ninject to create singletons for ICacheManager because it's a factory. Not sure if you're familiar with Ninject, but this is how I register it now, which is wrong because it creates a new instance every time.

	kernel.Bind(typeof(ICacheManager<>)).ToMethod((context) =>
	{
		// GenericArguments holds the actual type for ICacheValue used in the ICachManager property or argument
		return CacheFactory.FromConfiguration(context.GenericArguments[0], "defaultCache");
	});

So I tried changing the scope to singleton like this:

	kernel.Bind(typeof(ICacheManager<>)).ToMethod((context) =>
	{
		// GenericArguments holds the actual type for ICacheValue used in the ICachManager property or argument
		return CacheFactory.FromConfiguration(context.GenericArguments[0], "defaultCache");
	}).InSingletonScope();

but that doesn't work. I suspect it's because ToMethod doesn't support it but I'm not sure. Are you familiar with Ninject?

Thanks

**Comment by MichaCo** [comment]
Why does that not work for you?

The following code works totally fine in a console app:

            IKernel kernel = new StandardKernel();
            kernel.Bind(typeof(ICacheManager<>))
                .ToMethod((ctx)=> CacheFactory.FromConfiguration(ctx.GenericArguments[0], "defaultCache"))
                .InSingletonScope();

            var cacheA = kernel.Get<ICacheManager<string>>();

            var cacheB = kernel.Get<ICacheManager<string>>();

            cacheA.Put("key", "value");

            var a = cacheA.Get("key");
            var b = cacheB.Get("key");

And no I don't have a lot of experience with Ninject

**Comment by wujitouch** [comment]
So it turns out that the kernel (DI container) is disposed on every request. Solution is found here:
http://stackoverflow.com/a/11357824/867891

By the way, I don't think I saw anywhere in the documentation that "default" uses the Default instance of MemoryCache. I might have missed it though.

Thanks for your help. Loving the framework!

**Comment by MichaCo** [comment]
Sounds good :smile: 
Thanks!

**Comment by icnatejackson** [comment]
FYI... as of 11/27/2018, the WebApiContrib.IoC.Ninject nuget package has not been published containing the fix that @victor-ponce references.  The SOURCE CODE was changed in 2014, but no one ever published a version with the fix.  Just spent 4 days figuring that out.
