### ISSUE TITLE
CacheManager global key or region prefix

### ISSUE THREAD

**Issue by LRFalk01** [MichaCo/CacheManager#232]
I'm looking for a way to automatically prefix all cached items. I'm in a situation where an application runs an instance per customer, but the redis cache would be a single server. It's a fairly clear use case for regions I think, however it would really be nice if we could somehow define a global region that is automatically applied to an app domain. Is this possible?

**Comment by MichaCo** [comment]
Region in Redis has some overhead as CM has to keep a lookup with all keys in the region. It will also have some limitations over time. 

To just have a prefix on your keys, the easiest way is to do that on your side and just add a customer or "tenant" identifier on each key you store in the cache. String concatenation, that's the easiest thing ;)

If you can afford a Redis connection per customer, you can also use different Redis databases

**Comment by LRFalk01** [comment]
Thanks for the response. What I have setup now is a wrapper around BaseCacheManager<T> where when you set/get cache the key is prefixed with an instance specific key. Our internal CacheManagerFactory returns this instead of BaseCacheManager<T>. I'm going to test this tomorrow to make sure it works the way I think it should ;)

**Comment by LRFalk01** [comment]
My abstraction is working like a champ. Thanks for your help.
