### ISSUE TITLE
Logo proposal for CACHEMANAGER

### ISSUE THREAD

**Issue by ggabogarcia** [MichaCo/CacheManager#238]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by MichaCo** [comment]
Hi @ggabogarcia 
Sorry, I didn't respond in time, totally forgot.
I have kind of a logo for the nuget packages. 
If you want, sure, you can go ahead and figure something out which is more cool ;)

**Comment by ggabogarcia** [comment]
@MichaCo Thank you for your reply :) . I understand your responsibilities :), it's okay, I'll make some sketches and send them to you :)
