### ISSUE TITLE
Can I load configuration from a different file?

### ISSUE THREAD

**Issue by shepherds126** [MichaCo/CacheManager#24]
Hello, I would like to ask to create an instance of Cache Manager by configuration file（eg: cachemanager.config）, but  cachemanger.config in a configuration folder(eg:/Config/cachemanager.config), then ask you through
 CacheFactory.FromConfiguration <string> ("cacheName");
 Can not create cachemanager instance, there will be an exception : No section defined with name cacheManager, how can I create an instance cachemanager ? ? ? 
Thank you!

**Comment by MichaCo** [comment]
Sure, you totally can load other configuration files. Look at the configuration unit tests, there are many files in the /Configuration directory which are used by the unit tests... see https://github.com/MichaCo/CacheManager/blob/master/test/CacheManager.Tests/ValidConfigurationValidationTests.cs#L21 for example

Basically, you have to load the configuration before you initialize cache manager, something like this:

            string fileName = "blabla.config";
            string cacheName = "cache";
            var cfg = ConfigurationBuilder.LoadConfigurationFile(fileName, cacheName);
            var cache = CacheFactory.FromConfiguration<object>(cacheName, cfg);
