### ISSUE TITLE
Adding GetClone<T>

### ISSUE THREAD

**Issue by AeonDave** [MichaCo/CacheManager#242]
is possible to add a method (or maybe is alredy implemented?) which return a copy of the object itself.
Because sometimes i want to manipulate an object but i want to keep the original inside the cache

Ty

D

**Comment by MichaCo** [comment]
That's something you's have to deal with outside of the cache. There are many different ways doing that and highly depends on how complex the object you want to clone actually is.

So, no, that's not something I'd add to CacheManager, sorry ;)
