### ISSUE TITLE
Query : BinaryCacheSerializer with .Netstandard 2.0

### ISSUE THREAD

**Issue by shah-keyur** [MichaCo/CacheManager#246]
Hi MichaMo,

I have observed that when no serializer is defined then the BinraryCacheSerializer will be used as default.

However, the code was wrapped when!Netstandard then only use BinaryCacheSerializer.
When I test with.Netstandard 2.0 it works.

The comment also says "Binary serialization will not be available in some environments."
 
Can you explain in which environments it will not work? Or any specific reason to wrap the BinaryCacheSerializer into #If !Netstabdard.

Thanks,
Keyur

**Comment by MichaCo** [comment]
see #221
