### ISSUE TITLE
the problem of the CacheUpdateMode

### ISSUE THREAD

**Issue by BennetWang** [MichaCo/CacheManager#25]
I have seen the source code. I found that when you call Get method,you then call AddToHandles method.if the cache does not exist in the second layer,it may add,but if I manual change the value of the cache in the second layer,when I call the Get method,It can not be updated.Is it is a error or your purpose?

**Comment by MichaCo** [comment]
Well, that's how things work. 
If you modify values without calling Put, how should the cache manager know about those changes?

**Comment by BennetWang** [comment]
But,what you had wrote in the Documentation is that "All - instructs the Cache Manager to update all other cache handles".I call the Get Method which get value from the first layer,should not the cache  in the second layer be updated? I am sorry for my poor English.

**Comment by MichaCo** [comment]
Yes, in your case, the second layer will get the cache item added **if it doesn't exist already**.

Again, if you do a Get on your item and do changes to the item, you have to call Put to update all cache layers. Otherwise the changes might not be reflected in the cache.
