### ISSUE TITLE
Update StackExchange.Redis to latest version

### ISSUE THREAD

**Issue by SergeyLukashov** [MichaCo/CacheManager#251]
Hi @MichaCo!

Just wonder are there any plans to update CacheManager.StackExchange.Redis to use latest StackExchange.Redis (2.0+)? They have improved networking significantly in this release. So that'd be great to see this in CacheManager too.

Thanks!

**Comment by MichaCo** [comment]
Hi @SergeyLukashov,
Yes I've followed the release updates from Marc&co and will update CacheManager to support the new version whenever I find time to test it.

**Comment by SergeyLukashov** [comment]
Sounds great! Looking forward to check it out!

**Comment by keithl8041** [comment]
I am also keenly awaiting this upgrade to 2.0+ - happy to help with testing where possible.

**Comment by Onasss** [comment]
Yes, please! That would be very helpful.

**Comment by MichaCo** [comment]
CacheManager 2.0 beta packages do use the new Redis 2.0 client. 
Still have to do some testing and will release it soon

**Comment by MichaCo** [comment]
I decided to re-release 1.1.2 with just the Redis upgarde and some .NET Standard 2.0 support additions.
That's version 1.2.0 which [has just been released](https://github.com/MichaCo/CacheManager/releases/tag/1.2.0)!
