### ISSUE TITLE
No section defined with name cacheManager

### ISSUE THREAD

**Issue by cuibty** [MichaCo/CacheManager#26]
`<system.web>
  <compilation debug="true" targetFramework="4.5.2" />
  <httpRuntime targetFramework="4.5.2" />
  <caching>
    <outputCache defaultProvider="CacheManagerOutputCacheProvider">
      <providers>
        <add cacheName="cache" name="CacheManagerOutputCacheProvider" type="CacheManager.Web.CacheManagerOutputCacheProvider, CacheManager.Web" />
      </providers>
    </outputCache>
  </caching>
</system.web>`

No section defined with name cacheManager

**Comment by MichaCo** [comment]
Seems you are missing the `cacheManager` configuration section to configure the cache, the output cache provider should use.
Have a look at the sample site web.config https://github.com/MichaCo/CacheManager/blob/master/samples/CacheManager.Samples.Mvc/Web.config

**Comment by cuibty** [comment]
thanks , It has been resolved
