### ISSUE TITLE
Support for targeting .NET Core

### ISSUE THREAD

**Issue by ivansams** [MichaCo/CacheManager#261]
We are in the process of retargeting our application from .NET Framework 4.7.1 to .NET Core 2.1.

We now have the following warnings:

> Warning NU1701 Package 'CacheManager.SystemRuntimeCaching 1.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

It doesn't appear that we are experiencing any compatibility issues. However I just wanted to ask if there are any plans to release a version of this package that targets .NET Core?

**Comment by MichaCo** [comment]
see #221 

Tbh, I don't really know why you get that warning. Might be because the current 1.1.2 version of cachemanager only targets netstandard1.2.
That should be compatible with whatever .NET Core 2.x though.

Maybe give the 2.0 beta package of CacheManager a go. Let me know how that works.

**Comment by ivansams** [comment]
Thanks - it seems that the beta package doesn't give the same warning. I'll look forward to the release of v2.0 then!

**Comment by MichaCo** [comment]
just FYI, I'm currently testing the 2.0 beta bits in production without any issues so far

I still have to change a few things before releasing it, primarily internal changes, so, still a few weeks to go before that gets released

**Comment by jfritchman** [comment]
Any ideas when 2.0 will be released?
