### ISSUE TITLE
LastAccessedUtc not working on Redis

### ISSUE THREAD

**Issue by dorgold** [MichaCo/CacheManager#270]
CacheItem retrieved from Redis Cache has LastAccessedUtc always set to DateTime.UtcNow.

Expected behaviour:
LastAccessedUtc should be populated with the last time this Redis key was accessed

This can be implemented using the [OBJECT IDLETIME](https://redis.io/commands/OBJECT) command in Redis

**Comment by MichaCo** [comment]
Well, the key gets accessed when the item gets read or updated, and that's where the LastAccessedUtc field gets set.
It is mostly used to track expiration locally and I think its totally fine how and when its set for its purpose.
