### ISSUE TITLE
Isolation between two caches on the same redis

### ISSUE THREAD

**Issue by amirxnz** [MichaCo/CacheManager#271]
We have several different types of entites we are caching.
We are using SystemRuntimeCacheHandle with a redis backplane. 

Most types get updated very rarely, but one type gets updated a lot.

Only a specific subset of machines handle the volatile entity, but we only have one redis cluster. 
What i see is happening now is that for the OnAdd, I see that even though I gave the volitile one a different redis configuration name I am getting messages for all kinds of devices. I dont want my quiet machines to get so many notifications.

Is there a way to have two totally separate caches on the same redis backplane with each only getting notifications for the entities they are caching?

Thanks!

**Comment by MichaCo** [comment]
I might get your usecase wrong, but the backplane's channelname should help separating the events.

Per CacheManager configuration you can specify a different channel name for the backplane. Instances of those configurations should listen to events of that channel only.
Per default, they'd all use the same channel / get all events.
