### ISSUE TITLE
Store and Restore Cached Data

### ISSUE THREAD

**Issue by NGame1** [MichaCo/CacheManager#276]
Hi and thanks for the great library.
I'm working on a UWP project and using DictionaryHandle and JSON serializer for my project. 
Is there any way to save cached data into a file or somewhere else and restore them on the next launch?
Thanks.

**Comment by MichaCo** [comment]
No, cache!=persistent store.
There are many options to persist data though. Files, Databases..
Redis has different options to persist the cached data, too, in case that's an option for you.
