### ISSUE TITLE
GetCasted Exception ,I cannot solve it !

### ISSUE THREAD

**Issue by Rabbit021** [MichaCo/CacheManager#277]
###  GetCasted Exception ,I cannot solve it !
Exception:[A]System.Collections.Generic.List`1[DataPlamtformCommon.Models.Floor] cannot be cast to [B]System.Collections.Generic.List`1[DataPlamtformCommon.Models.Floor]. Type A originates from 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Private.CoreLib.dll'. Type B originates from 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Private.CoreLib.dll'.
 StackTrace:   at CacheManager.Core.Internal.BaseCache`1.GetCasted[TOut](Object value)
   at ServiceCore.Extensions.CacheManagerExt.GetFromCache[T](ICacheManager`1 basicCache, String key) in E:\Develop\GeneralCloudPlatform\ServiceCore\Extensions\CacheManagerExt.cs:line 118

**Comment by Rabbit021** [comment]
###  I use it in asp.net core 2.0!
 it trow exception when I use redis cache ,but i use dictionarycache it is ok!

**Comment by MichaCo** [comment]
The error might be misleading, looks more like a de-serialization issue with your `Floor` object. 
Could you do a simple `Get`, that might give a better idea.
