### ISSUE TITLE
Conflict of StackExchange.Redis vs StackExchange.StrongName.Redis

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#279]
Hi,
I am using CacheManager library for last couple of years. It's very helpful to me. I am facing a issue when i tried to use CacheManager and RedLockNet(Distributed Locking using Redis) as RedLockNet Uses(StackExchange.Redis) . As both the libraries having IConnectionMultiplexer now there is a conflict . As both requires IConnectionMultiplexer but from different name spaces. Is there any way i can resolve?

**Comment by MichaCo** [comment]
Upgrade both libraries to the version where they use StackExchange.Redis 2.x?
CacheManager uses the old strong named package till version 1.1.2. 
CacheManager 1.2 uses the newer one..

**Comment by vijay8059** [comment]
Yes they are using StackExchange.Redis 2.x
