### ISSUE TITLE
What about a plugable value converter / serializer?

### ISSUE THREAD

**Issue by pajo** [MichaCo/CacheManager#28]
Is there a plan to make redis converter plugable, so we can change default implementation. Right now we're stuck with very inflexible and not very performant (both in speed and size) binary serializer. It's fine default, but adding redis support to existing project can be nightmare as you need to go over all project and mark all classes as serializable or create proxies that can be serialized if you don't own class(these are all runtime errors), while all this can be avoided using different or custom serializer.

**Comment by MichaCo** [comment]
You are totally right. binary serializer is not the happy path in terms of performance. That being said, CacheManager uses a serialization path only if the value you store in cache is actually a complex object. If you store simple values, the StackExchange.Redis component can convert to string already, those values will not get "extra" de-/serialized...

And yes, my plan was to make the serialization plugable to use JSON, or protobuffer for example. I simply had no time so far to implement that ;)

Would be basically a simple interface in core which has the serialization methods. 
Then have separated assemblies for JSON and Protobuffer etc..., with the corresponding dependencies.
And the CacheManagerConfiguration would take the type of the serializer implementation.
That way you can configure serialization per object type you want to cache, and you could write your own serialization if needed and just pass in the type.

Any thoughts/other ideas?

**Comment by pajo** [comment]
I think interface is fine, what you might consider is making value converters agnostic to cache provider implantation so you can reuse them in other out of process caching providers.

**Comment by MichaCo** [comment]
Implemented in 0.7
