### ISSUE TITLE
Redis Cache Synchronisation

### ISSUE THREAD

**Issue by LukeRH** [MichaCo/CacheManager#284]
Hi,
I am using CacheManager with a Redis backplane and an in-process cache for each process. When i update an item in the cache in one process and then get the same item immediately after from another process, is it possible that the in-process cache is not up to date yet and i will get the old value? 

Thanks 
Luke

**Comment by MichaCo** [comment]
While the backplane delivers the "change" message to all connected listeners, yes, you can end up with stale data.
The message delivery is very fast in general, but it depends on overall system and network performance, same as everything else with Redis.

**Comment by LukeRH** [comment]
Thanks for the clarification
