### ISSUE TITLE
can't found the redis's extensions method[.net 4.0/nuget/0.6.1]

### ISSUE THREAD

**Issue by BillyChan501** [MichaCo/CacheManager#29]
![image](https://cloud.githubusercontent.com/assets/470915/11611395/53ad86ee-9c06-11e5-9642-9d93bafb7b40.png)

**Comment by MichaCo** [comment]
I cannot reproduce this. 
When I create a new console app targeting `.net 4.0` and install the CacheManager SystemRuntimeCaching and StackExchange.Redis packages, it just works.

If you still have that issue, please create a github repo and upload a simple project where you can reproduce the behavior.

That being said, you might get warnings under .net 4.0, something like 

> warning MSB3268: The primary reference "StackExchange.Redis, Version=1.0.316.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "StackExchange.Redis, Version=1.0.316.0, Culture=neutral, processorArchitecture=MSIL" or retarget your application to a framework version which contains "System.Runtime, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

In that case, update the BCL packages or simply the StackExchange.Redis nuget to the latest version...
