### ISSUE TITLE
How to only store value in CacheManager

### ISSUE THREAD

**Issue by giangcoi48k** [MichaCo/CacheManager#294]
I am intending to use CacheManager for my netcore project.
I configured the following
```C#
var jss = new JsonSerializerSettings
{
	NullValueHandling = NullValueHandling.Ignore,
	ReferenceLoopHandling = ReferenceLoopHandling.Ignore
};

const string redisConfigurationKey = "redis";
services.AddSingleton(typeof(ICacheManagerConfiguration),
	new CacheManager.Core.ConfigurationBuilder()
		.WithJsonSerializer(serializationSettings: jss, deserializationSettings: jss)
		.WithUpdateMode(CacheUpdateMode.Up)
		.WithRedisConfiguration(redisConfigurationKey, config =>
		{
			config.WithAllowAdmin()
				.WithDatabase(0)
				.WithEndpoint("localhost", 6379);
		})
		.WithMaxRetries(100)
		.WithRetryTimeout(50)
		.WithRedisCacheHandle(redisConfigurationKey)
		.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))
		.Build());

services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
```
It work well. But when I looked into redis, there are redundant keys in hash, like timeout, version, defaultExpiration,... For example, I puted one key test like `_cacheManager.Put("Test", "Test Value");`, the value I got:
![image](https://user-images.githubusercontent.com/12107588/69979885-b885aa00-1561-11ea-8047-9ee2a03727f8.png)
I think it's a waste of memory if there are lots of keys with small value. So, is there any way only store value and key, and ignore the redundant keys? 
Sorry for my bad English

**Comment by MichaCo** [comment]
Nope that's how CM works today. The meta data is needed to allow timeouts per cache key and support sliding expiration and all those things.
It is a bit of an overhead but I think it's a good trade-off.

**Comment by ndrwrbgs** [comment]
@giangcoi48k I'd gander that if the overhead is too much, you're going to be needing to have fine-grained control over your cache implementation anyway (custom data types, eviction mechanisms etc). But I would personally try it and only decide it's too much if performance tests say so.
