### ISSUE TITLE
Possible Memory Leak caused by OnCacheSpecificRemove event subscription in BaseCacheManager class

### ISSUE THREAD

**Issue by NazmiAltun** [MichaCo/CacheManager#295]
Is it possible that the following line  causes memory leak? 

https://github.com/MichaCo/CacheManager/blob/4385c06a409e9736a7531c5e11003032b8a4c151/src/CacheManager.Core/BaseCacheManager.cs#L86
There is a subscription to OnCacheSpecificRemove  event  but in  dispose method of  `BaseCacheManager `class  there is no unsubscribe call.

**Comment by MichaCo** [comment]
That's on initialization, done once ever for a CM instance.

So, **no**, because CM is supposed to live as singleton this will run only once ever.

**Comment by NazmiAltun** [comment]
In that case i am closing this issue
