### ISSUE TITLE
Nuget for CacheManager.SystemRuntimeCaching not targeting netstandard2.0

### ISSUE THREAD

**Issue by pergardebrink** [MichaCo/CacheManager#313]
I was looking at a build warning I got when building against .NET Core claiming CacheManager.SystemRuntimeCaching was restored using .NET Framework. 

It seems as the csproj for CacheManager.SystemRuntimeCaching builds a netstandard2.0 version, but it does not appear to have been published to the NuGet feed? Or am I missing something?

**Comment by nflash** [comment]
It seems the last publish of these packages into NuGet was in late 2018. 
@MichaCo Does this mean the library is no longer being actively maintained?

@pergardebrink for .net core why not use CacheManager.Microsoft.Extensions.Caching.Memory?

**Comment by MichaCo** [comment]
The beta packe supports netstandard 2.0.
If you really have to use runtime caching, just use that for now, or use any other memory cache.

Regarding releases, there hasn't been any release lately because I did not have any time to add new features, hence no need to release anything.

**Comment by robertcoltheart** [comment]
Can this be moved to a non-beta release at least? We're facing the same issue as above.

**Comment by MichaCo** [comment]
Yeah when I find some time this year, there will be a release. I got some vacation this month, lets see ;)

**Comment by robertcoltheart** [comment]
Any update on this please?
