### ISSUE TITLE
MichaCo.net certificate expiry

### ISSUE THREAD

**Issue by OzBob** [MichaCo/CacheManager#315]
![image](https://user-images.githubusercontent.com/1796771/83598644-d679a900-a59c-11ea-813c-17b40a521eda.png)

The certificate to https://michaco.net/blog/CacheManagerReleaseOneDotOneNewFeaturesAndFuture
in Chrome says Warning! expired because it is IssuedTo: *.azurewebsites.net
but the certificate for https://cachemanager.michaco.net/
in Chrome is OK because it is IssuedTo: cachemanager.michaco.net

**Comment by MichaCo** [comment]
The naked domain michaco.net doesn't have a certificate right now. Azure App Service's build in certificates (free version) only works with non naked domain for whatever reason unfortunately. Was going to change all links and the default domain to www.michaco.net, which is already configured.
Thanks for reminding me ^^
