### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by bencyoung** [MichaCo/CacheManager#316]
Hi,

I just wanted to check if this project is still active? It works well for us in the current version but there don't seem to have been any changes for around 8 months and the latest issues are going unanswered.

It's not an issue if it is, these things happen, but it would be good to get a statement if we could

Thanks!

**Comment by MichaCo** [comment]
The project is still maintained by me, there is just not much change happening right now for many reasons, mostly lack of time.

I still support consumers and post answer to issues worth answering ;)

**Comment by ndrwrbgs** [comment]
I know I have a dependency on it, and similarly if there was something proposed that was pretty major I'd engage on it :)
Thanks @MichaCo!

**Comment by bencyoung** [comment]
That's great, thanks for maintaining this project!
