### ISSUE TITLE
Any plan for 2.0 final release?

### ISSUE THREAD

**Issue by tonyqus** [MichaCo/CacheManager#317]
I notice that the latest nuget version is 2.0 prerelease instead of final release. Is there any plan for that?

**Comment by nunoguerreirorosa** [comment]
I would like to know that as well.  Thanks

**Comment by ipoetry** [comment]
I also wanted to know. Thanks

**Comment by MichaCo** [comment]
Hi guys, 
is there any feature missing in the currently actual released version missing which would be in 2.0 beta?

But yeah, I get it, its been some time now ^^

**Comment by tonyqus** [comment]
Btw, how about async interfaces? Have they already been included in 2.0?

**Comment by MichaCo** [comment]
no

**Comment by tonyqus** [comment]
Hmm... maybe you can put it in 2.1 roadmap if 2.1 exists :D  Btw, I did put CacheManager in our company's code this week. Nice work.

**Comment by nunoguerreirorosa** [comment]
> Hi guys,
> is there any feature missing in the currently actual released version missing which would be in 2.0 beta?
> 
> But yeah, I get it, its been some time now ^^

I don't think there is a feature coming on 2.0 that I personally need but 2.0 has been on beta for a long time now and improvements are always welcome. It would be nice to see some activity on the CacheManager since its a very good library and it would be a shame to see it completely outdated in comparison to other multilevel cache libraries. 👍 :)

**Comment by nunoguerreirorosa** [comment]
I actually need CacheManager.SystemRuntimeCaching support for .net standard which is in the latest release 2.0. Any way that can be released ?  Thank you.

**Comment by martyt** [comment]
@nunoguerreirorosa I also need that - we've converted our app from framework to core / standard 2.0 and we're using the  2.0 beta of CacheManager.SystemRuntimeCaching - would very much like to upgrade to a full 2.0 release.

**Comment by wa926talent** [comment]
I also wanted to know. Thanks

**Comment by tonyqus** [comment]
https://github.com/MichaCo/CacheManager/issues/309#issuecomment-714874365
