### ISSUE TITLE
Using multi-level cache, with 2nd level to disk

### ISSUE THREAD

**Issue by taebae027** [MichaCo/CacheManager#321]
Hi,

I apologize in advance if this has been answered elsewhere or is available in the documentation, but i haven't been able to find the answer.

I'm looking to create a two-tiered cache with the first being in memory and the second stored in disk (i.e. FileCache, which extends System.Runtime.Caching.ObjectCache)
Is there a way to do this? Any help would be appreciated.

Thanks.

**Comment by MichaCo** [comment]
Hi @taebae027,
Did you figure something out so far?

This is more a conversation then an issue. 

My suggestion would be to write your own, file based, cache handle, which does exactly what you need with your file types and data structures.

**Comment by ndrwrbgs** [comment]
The FileCache package has some limits on key length and contents so
(shameless plug) I made a sqlite version to handle disk caching. Try
FileCache first (it's more widely used) but don't feel you need to write
your own (unless you wish to!).
