### ISSUE TITLE
. net core does not support WithBinarySerializer methods

### ISSUE THREAD

**Issue by dengyangxi** [MichaCo/CacheManager#323]
I have two projects operating a redis.
One is the . Net framework and the other is the . Net CORE 

This causes the. Net framework project to write to a cache  .    . Net core project that cannot be serialized

But. Net core does not have withbinaryserializer. How can I replace it  ?

`
**#if !NETSTANDARD2**

        /// <summary>
        /// Configures a <see cref="BinaryCacheSerializer"/> to be used for serialization and deserialization.
        /// </summary>
        /// <returns>The builder part.</returns>
        public ConfigurationBuilderCachePart WithBinarySerializer()
        {
            Configuration.SerializerType = typeof(BinaryCacheSerializer);
            return this;
        }

        /// <summary>
        /// Configures a <see cref="BinaryCacheSerializer"/> to be used for serialization and deserialization.
        /// </summary>
        /// <param name="serializationFormatter">The <see cref="BinaryFormatter"/> for serialization.</param>
        /// <param name="deserializationFormatter">The <see cref="BinaryFormatter"/> for deserialization.</param>
        /// <returns>The builder part.</returns>
        public ConfigurationBuilderCachePart WithBinarySerializer(BinaryFormatter serializationFormatter, BinaryFormatter deserializationFormatter)
        {
            Configuration.SerializerType = typeof(BinaryCacheSerializer);
            Configuration.SerializerTypeArguments = new object[] { serializationFormatter, deserializationFormatter };
            return this;
        }

**#endif**
`

**Comment by MichaCo** [comment]
Binary Serialization isn't supported in .NET Core, at least not to that degree that it would work for this library which means you have to use any other serializer. There are a couple build in ones coming in additional NuGets, or you serialize your data yourself and then cache it.

**Comment by dengyangxi** [comment]
thank you  ！ ！~
