### ISSUE TITLE
ArgumentNullException in TryGetValue

### ISSUE THREAD

**Issue by zoizer** [MichaCo/CacheManager#324]
When calling MicrosoftConfigurationExtensions.LoadRedisConfigurations, the resulting RedisConfiguration is created with the default constructor meaning the RedisConfiguration._configurationOptions & RedisConfiguration._connectionString remains uninitialized if no explicit connection string was added. This could probably be solved by calling and storing the result from RedisConfiguration.CreateConfigurationOptions() and ToString().

Crash occurs in RedisConnectionManager.Connect().

**Comment by MichaCo** [comment]
Not really sure but that simply sounds unsupported / not intended use
I'll leave it open to check out at some point. If you could provide a reproduceable example, that would make it easier to understand what the problem is
