### ISSUE TITLE
Why CacheManager  is not CLS-compliant?

### ISSUE THREAD

**Issue by tatarincev** [MichaCo/CacheManager#33]

**Comment by MichaCo** [comment]
There is actually no particular reason. Actually, all new .net and asp.net packages are not marked as CLS compliant. But there is also no real value in doing so, or is it?

I can add AssemblyInfos where needed anyways when I find some time

**Comment by MichaCo** [comment]
@tatarincev 0.7.1 is now released and all packages should be marked as CLS compliant again
