### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by NinjaCross** [MichaCo/CacheManager#330]
I really like this project very much, but I'm a bit concerned about the fact that there are still many (old) opened issues, and it seems it's no longer actively maintained.
My main concern is related to the usage of this library into a couple of big projects I'm going to start this year.
My customers are raising questions about the potential impact caused by the usage of abandoned / not evolving dependencies.
Are there future plans and evolutions for this project in the foreseeable future ?

**Comment by MichaCo** [comment]
Its a fair question.
My plan is to spend a bit more time this year on OS projects again.
Not sure what exactly that means for CacheManager though. 
That being said, I'm using CacheManager in a major project at work extensively, too, meaning, the library will not go away anytime soon and I'll continue to fix bugs.

I was also planning a V2 with a simplified design / smaller feature set, which will not be compatible with V1 at all. 
Primarily to get rid of a lot of code and currently supported things I cannot really test and almost noone is using. But also to improve things I'm not happy with in the current version.

Hope that helps ^^

**Comment by MichaCo** [comment]
/closing this for now, 
I'm pretty close to releasing 2.0 - see #340, I hope you guys can help testing it ^^
