### ISSUE TITLE
Infinite loop when trying to add a key to an slave node (Redis)

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#34]
In my current setup I have one master node and two slaves (readonly), for the purpose of testing in the config file I just defined the endpoints of the slaves node. In this scenario when I try to add a key to the slave node CacheManager gets stuck trying to add the key (confirmed while monitoring the slave node). Also confirmed that StackExchange Redis raise an exception on this scenerio, so I suppose the problem is with the retry part implemented in the handle

**Comment by MichaCo** [comment]
I'd consider that as a configuration error. But I'll at least add a check that at least one endpoint is writeable.

**Comment by TMiNus** [comment]
Imagine that you have a master and two slaves with a sentinel in case of a failure, if the master goes down the sentinel will promote an slave to master but in that small windows CacheManager could get stuck trying to write to a slavenode

**Comment by MichaCo** [comment]
Nope that is all handled by the Stackexchange.Redis client.
