### ISSUE TITLE
Supporting .NET Standard 2.1

### ISSUE THREAD

**Issue by jkatsiotis** [MichaCo/CacheManager#347]
Hi Michael,

Any plans to support .NET Standard 2.1?

**Comment by MichaCo** [comment]
why? 

netstandard 2.1 is backwards compatible to netstandard 2.0. 
As long as I'm not using any APIs which exist only in the netstandard 2.1 API surface,  I don't have to target that and netstandard 2.0 is totally fine.
Anything released right now which targets netstandard 2.0 will also work with your libraries when you target netstandard 2.1...

But yes, I'm making changes as needed, see #340 for example.
