### ISSUE TITLE
Commands Flags (Redis) when getting or adding a key

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#35]
In a replication group adding a key always goes to the master node (as it should), but when reading, it goes also to the master node, it will be better to give the clients the option of defining the Commands Flags when they are working with a redis handle or hardcode the PreferSlave flag on every get operation

**Comment by MichaCo** [comment]
I'm not sure why get calls should always go to the slave. Usually slaves are used for replication and fail over. You can even setup the master to not store the data on disk and only the slave handles persistence. Not even sure if that would work with clusters at all?

Anyways, I don't really see a big need for that, but it could be implemented as a configuration option to override the defaults (which is master).

**Comment by TMiNus** [comment]
If the master is under heavy load, it would be nice to be reading also from the slaves nodes so we can free up some resources on master. I guess it depends on the size of the operation you are running but I can see the scenario

**Comment by MichaCo** [comment]
Just tested a few things. First of all, master to slave replication is non blocking async. So it could happen at any point that the items are not even on the slave although they just have been added.

Then, when retrieving an item, I also have to update e.g. sliding expiration. That can only happen on the master if the slave is readonly => doesn't work in one go (one lua script).

During update, I have to get the cache item to get the "old" value and then update to a new value. Those checks are pretty critical and shouldn't go on different servers.

=> will not be changed

**Comment by TMiNus** [comment]
All valid points, I didn´t think in the sliding expiration, but yes that should all happen in master. Although I think at least for items when absolute expiration or no expiration at all could be implemented.
