### ISSUE TITLE
Is there a plan to release a stable 2.x version ?

### ISSUE THREAD

**Issue by NinjaCross** [MichaCo/CacheManager#354]
My customers are worried of using beta-grade packages.
As far as I can see, the version 2.0.0 is in beta stage since the 11/15/2018
Is there a plan to release a 2.0.0 non-beta ?

**Comment by MichaCo** [comment]
yeah if you look at other issues and discussions and the open PR you'll see its in the works and I'm almost done with it.
I just have very limited time right now because of work. But will be release soon™
