### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by Oleg26Dev** [MichaCo/CacheManager#368]
Or it is abandoned? No changes some years, issues without answers. Not clear what about NET 5, NET 6?

**Comment by MichaCo** [comment]
It works just fine in production on .NET 5 and NET 6 for us, so yeah, works just fine.

**Comment by Oleg26Dev** [comment]
Thank you! Great!

**Comment by tonyqus** [comment]
@MichaCo If I'm willing to help maintain this project, do you still accept PR?
