### ISSUE TITLE
New logging package using NLog directly

### ISSUE THREAD

**Issue by MichaCo** [MichaCo/CacheManager#38]
The only currently available logger uses the Microsoft.Extensions.Logging package.
I'd like to have at least one other implementation, and one of them should be using the latest NLog directly so that we don't have deps to the Microsoft stack.

**Comment by brianlocke** [comment]
May I suggest LibLog?

**Comment by MichaCo** [comment]
Yup, looks good, too. Why not ;)

----- Ursprüngliche Nachricht -----
Von: "brianlocke" <notifications@github.com>
Gesendet: ‎25.‎02.‎2016 23:06
An: "MichaCo/CacheManager" <CacheManager@noreply.github.com>
Cc: "MichaC" <kletterer@web.de>
Betreff: Re: [CacheManager] New logging package using NLog directly (#38)

May I suggest LibLog?

---

**Comment by wenisman** [comment]
i have a plugin for serilog if you're interested?

**Comment by MichaCo** [comment]
I'm actually not sure if it makes too much sense to create additional packages/wrappers for each logging framework because the Microsoft.Extensions thing does that abstraction already.
Seems there is already one for serilog https://github.com/serilog/serilog-extensions-logging
