### ISSUE TITLE
Allow to add null values in cache

### ISSUE THREAD

**Issue by diadistis** [MichaCo/CacheManager#41]
Is there a reason for not allowing null values?

**Comment by MichaCo** [comment]
Yes, returning `Null` on Get means the key has not been stored in the cache.

**Comment by killergege** [comment]
This is not a really safe way to test if a key is not in cache... Get<int> would return 0...
Having a value in cache set to null and not having the key in cache is not really the same (it could be expensive to calculate a value and obtaining null... if you can't cache that, it's a problem). 

I strongly suggest to add a method to check that the key exist and remove this limitation, as suggested in issue #46

**Comment by MichaCo** [comment]
as mentioned in #46 you can always call `GetCacheItem` which always returns null if the key doesn't exist in the cache no matter what type of data you are storing with the item. That's totally safe I guess?

If I find some time I will double check what the impact is if I allow null values being stored. 
Only problem is, it is not possible to store NULL as value of a key or value of a hash field in Redis...
