### ISSUE TITLE
CacheManager should support Redis < 2.6

### ISSUE THREAD

**Issue by rebulanyum** [MichaCo/CacheManager#42]
Hi. I'm using Redis4You hosted redis server. And the following configuration works fine. When the code comes to line `Cache.Add("a", "b");`, then it stucks there for an infinite time. When I monitor the Redis server I see the console with full of PING there. What is the problem here?
```csharp
    static class Program
    {
        static readonly ICacheManager<string> Cache = CacheFactory.Build<string>("Test", cbcp =>
        {
            cbcp.WithSystemRuntimeCacheHandle("testCache")
                .And
                .WithRedisConfiguration("redis", rcb =>
                {
                    rcb.WithEndpoint("<XXX>", 1111)
                       .WithPassword("<YYY>")
                       .WithAllowAdmin()
                       .WithDatabase(1);
                })
                .WithMaxRetries(100)
                .WithRetryTimeout(10)
                .WithRedisBackPlate("redis")
                .WithRedisCacheHandle("redis", true);
        });
        static void Main(string[] args)
        {
            /* It stucks in the first line. */
            Cache.Add("a", "b");
            Console.ReadLine();
        }
    }
```

I debugged the code and the LuaScripts you've provided such as the one below causes an error: 

```lua
local result=redis.call('HMSET', KEYS[1], 'value', ARGV[1], 'type', ARGV[2], 'expiration', ARGV[3], 'timeout', ARGV[4], 'created', ARGV[5])
if ARGV[3] ~= '0' and ARGV[4] ~= '0' then
    redis.call('PEXPIRE', KEYS[1], ARGV[4])
else
    redis.call('PERSIST', KEYS[1])
end
return result
```

The reason is the RedisCacheHandle class's void `LoadScripts()` method doesn't check the `server.Features.Scripting`; since Redis4You uses redis version 2.4 it's forbidden to use luascripts in the way you provided. You shall give support for v 2.4 too.

**Comment by MichaCo** [comment]
Using the server features to determine if CacheManager can run and at least throw an exception otherwise would be a good improvement I guess.

Regarding supporting version 2.4, well, 2.4 is pretty old already, don't know if the effort is really worth it -.-
Lua Support has been added in 2.6, 2.6 and later should work just fine. v2.6 has been released on 22 Oct 2012...

**Comment by rebulanyum** [comment]
> Using the server features to determine if CacheManager can run and at least throw an exception otherwise would be a good improvement I guess.

You're right; or maybe you should make a change request on StackExchange.Redis library since the exception is thrown from their own structures (LuaScript, RedisServer etc.)

**Comment by MichaCo** [comment]
This will be fixed in the next release, I tested everything on a 2.4 server, seems to work.

**Comment by rebulanyum** [comment]
Thank you.
