### ISSUE TITLE
Backplane type not found

### ISSUE THREAD

**Issue by youliny** [MichaCo/CacheManager#45]
in web.config i config the cache like this:
<cache name="myCache" updateMode="Up" enableStatistics="false" enablePerformanceCounters="true" 
             backplaneName="redis" backplaneType="CacheManager.Redis.RedisCacheBackplane, CacheManager.StackExchange.Redis">
        <handle name="sysCache" ref="sysCacheHandle" />
        <handle name="redis" ref="redisHandle" expirationMode="None" isBackplaneSource="true" />
      </cache>
but when i runing the application the error take out:

Backplane type not found, CacheManager.Redis.RedisCacheBackplane, CacheManager.StackExchange.Redis. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.InvalidOperationException: Backplane type not found, CacheManager.Redis.RedisCacheBackplane, CacheManager.StackExchange.Redis.

**Comment by MichaCo** [comment]
Which version of CacheManager are you using? Backplane got renamed from BackPlate in version 0.8, see release notes and #44

And do you have installed the `CacheManager.StackExchange.Redis` nuget package?

**Comment by youliny** [comment]
I check my version of CacheManager is 0.8. But version of CacheManager.StackExchange.Redis is 0.74
 update the redis to 0.8. everything is ok, thx very much

**Comment by MichaCo** [comment]
ok cool ;)
