### ISSUE TITLE
Configuring Redis distributed only

### ISSUE THREAD

**Issue by gthelp** [MichaCo/CacheManager#47]
I was trying to have a Redis only solution in MVC core
In startup.cs I configured cache and injected it into Singleton
But it tells me that no cache handles are configured.

    var cache = CacheFactory.Build("cacheName", settings => settings
               .WithJsonSerializer()
               .WithUpdateMode(CacheUpdateMode.Up)
               .WithRedisConfiguration("redis", config =>
                       {
                           //config.WithAllowAdmin()
                           //.WithDatabase(0)
                           config.WithEndpoint("Devgreen", 6379);
                       })
                //.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromHours(29))
                );
            services.AddSingleton<ICacheManager<object>>(serviceProvider => cache);

**Comment by MichaCo** [comment]
yup, you added a redis configuration which is fine, but you never actually added a redis cache handle.
There is a call to `.WithRedisCacheHandle` missing, like the following

    var cache = CacheFactory.Build("cacheName", settings => settings
        .WithJsonSerializer()
        .WithUpdateMode(CacheUpdateMode.Up)
        .WithRedisConfiguration("redis", config =>
        {
            //config.WithAllowAdmin()
            //.WithDatabase(0)
            config.WithEndpoint("Devgreen", 6379);
        })
        .WithRedisCacheHandle("redis"));

**Comment by gthelp** [comment]
That solved that one. Knew it was something simple. 

Thanks
