### ISSUE TITLE
CacheItem not serializing correctly

### ISSUE THREAD

**Issue by gthelp** [MichaCo/CacheManager#48]
I am trying to set a cacheitem into the cache. 
Since I had to inject the cache as an type object when I try to add cacheitem it complains that cant convert between ClientPrefernce and object. How could I convert or inject CacheManager to handle different complex types serialized with JSON? Am I missing something simple?

Thanks

startup.cs
var cache = CacheFactory.Build("cacheName", settings => settings
               .WithJsonSerializer()
               .WithUpdateMode(CacheUpdateMode.Up)
               .WithSystemRuntimeCacheHandle("inProcessCache")
                );
            services.AddSingleton<ICacheManager<object>>(serviceProvider => cache);

class
private readonly ICacheManager<object> _cache;

 public DoController(ICacheManager<object> cache): base()
        {
            this._cache = cache;
        }

function...
var item = new CacheItem<ClientPreference>(
    cacheKeyLookup, preference, ExpirationMode.Absolute, TimeSpan.FromHours(29));
this._cache.Add(item);

**Comment by MichaCo** [comment]
First of all, the cache you configured wouldn't use serialization at all. You only have one System.Runtime cache handle which is storing data in-memory and doesn't require/use serialization.

Could you provide a reproducible example and the exact error message? With the code snippets you posted, I cannot tell what this is about ;)

**Comment by gthelp** [comment]
Determined that was a coding issue, I was putting the wrong object in cache in 1 place and trying to cast it to another object in other location. User Error.
Sorry for confusion.

**Comment by MichaCo** [comment]
ok cool ;)
