### ISSUE TITLE
Configuration for Logging

### ISSUE THREAD

**Issue by gthelp** [MichaCo/CacheManager#49]
On initial startup using microsoft logging, I see the the redis connection information.
I would like to see the trace logic of the decision making when I addorupdate or get, but am not seeing it.  Any suggestions? 

Thanks

My project.json
"Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
"CacheManager.StackExchange.Redis": "0.8.0",
    "CacheManager.Serialization.Json": "0.8.0",
    "CacheManager.SystemRuntimeCaching": "0.8.0",
    "CacheManager.Microsoft.Extensions.Configuration": "0.8.0-beta-1219",
    "CacheManager.Microsoft.Extensions.Logging": "0.8.0-beta-1219"

my startup.cs

public void ConfigureServices(IServiceCollection services)
        {

//https://github.com/MichaCo/CacheManager
            var cache = CacheFactory.Build("cacheName", settings => settings
            .WithMicrosoftLogging(f => f
                .AddConsole(minLevel: LogLevel.Debug)
                .AddDebug(minLevel: LogLevel.Debug)
                )
                .WithJsonSerializer()
                .WithUpdateMode(CacheUpdateMode.Full)
                .WithSystemRuntimeCacheHandle("inProcessCache") //use local cache and sync with redis
                .And
                .WithRedisConfiguration("redis", config =>
                {
                    config.WithAllowAdmin()
                        .WithDatabase(0)
                        .WithEndpoint("redistest", 6379);
                })
                .WithMaxRetries(1000)
                .WithRetryTimeout(100)
                .WithRedisBackplane("redis")
                .WithRedisCacheHandle("redis", true)
                .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes(30)) /*allow 30 minutes unused cache before blast*/
                .EnableStatistics().EnablePerformanceCounters()
                );
            services.AddSingleton<ICacheManager<object>>(serviceProvider => cache);
}

**Comment by MichaCo** [comment]
See this example: https://github.com/MichaCo/CacheManager/blob/dev/samples/CacheManager.Examples/Program.cs#L89

For some reason, the rc1 release of MS Logging uses `Debug` level as `Verbose`. They changed it already in rc2 so until rc2 is released and I upgraded the logging package, you have to use debug as the minimum log level to get verbose log messages.

For some strange reason, in rc1, you also have to set the min log level of the logger factory to `Debug`, otherwise it will not log those messages (this will change in rc2, too)

Try add `f.MinimumLevel = LogLevel.Debug;` within the `WithMicrosoftLogging` builder

**Comment by gthelp** [comment]
That worked. I had seen that information, but I put the minimum level in the wrong place. Here is my startup.cs settings for anyone else who has run in to this issue. Thanks for the quick response.

//https://github.com/MichaCo/CacheManager
            var cache = CacheFactory.Build("cacheName", settings => settings
                .WithMicrosoftLogging(f =>
                    {
                    f.MinimumLevel = LogLevel.Debug;
                    f.AddConsole(minLevel: LogLevel.Debug);
                    f.AddDebug(minLevel: LogLevel.Debug);
                    })
                .WithJsonSerializer()
                .WithUpdateMode(CacheUpdateMode.Full)
                //.WithSystemRuntimeCacheHandle("inProcessCache").And //use local cache and sync with redis
                .WithRedisConfiguration("redis", config =>
                {
                    config.WithAllowAdmin()
                        .WithDatabase(0)
                        .WithEndpoint("redistest", 6379);
                })
                .WithMaxRetries(1000)
                .WithRetryTimeout(100)
                //.WithRedisBackplane("redis").WithRedisCacheHandle("redis", true)
                .WithRedisCacheHandle("redis", false)
                .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes(30)) /*allow 30 minutes unused cache before blast*/
                //.EnableStatistics().EnablePerformanceCounters()
                );
            services.AddSingleton<ICacheManager<object>>(serviceProvider => cache);
