### ISSUE TITLE
Configuring System.RuntimeCaching from App/Web config

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#53]
I have noted that you can configure System.RuntimeCaching from the Json file using  Microsoft.Extension (I think this feature is pretty cool, so first of all congrats on that one). I was checking out if you could do the same from web/app config and it seems that there is no way other than hard code the configuration for the System.RuntimeCaching in the code

**Comment by TMiNus** [comment]
I checked the documentation again and it seems there is a way of doing it. Awesome!!

**Comment by MichaCo** [comment]
yup there should be all kinds of options available. Let me know if you find anything missing

**Comment by TMiNus** [comment]
I think the only thing that is missing is the configuration for the logger. The rest is all good
