### ISSUE TITLE
Add GZip Support to JsonSerializer

### ISSUE THREAD

**Issue by fgideali** [MichaCo/CacheManager#55]
We have been using the JsonSerializer with Redis Backplate for a little while now.

Json tends to be very verbatim in some situations and we had multiple issues where structures would take as little as 500k in MemoryCache and up to 10m in Redis.

based on this thread: http://stackoverflow.com/questions/6556631/compressing-strings-before-putting-them-in-redis-does-it-make-sense
we ended up forking the JsonSerializer, creating a custom GzJsonSerializer using the System.IO.Compression.GZStream for those specific situations. 
The Redis structures are now closer to the expected 500k.

Since we use a distributed redis server. Compression Cost is way less than Bandwidth, speeding up everything at the same time.

--
A GzJsonSerializer overwrite or a configurable compression flag could be a nice improvement.

**Comment by MichaCo** [comment]
Sounds interesting

Feel free to submit a PR which adds your implementation to the Json Serializer package.

**Comment by MichaCo** [comment]
That's now merged. Thanks again!

Might take me some time to get all the builds running again and get 0.9 released though ;)
