### ISSUE TITLE
Using non distributed caches as Backplane

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#59]
I know for a fact that the synchronization feature of the **Backplane** is implemented with the **Redis Pub/Sub** feature but I was wondering if **MemoryCache** or **Dictionary** can be used as **Backplane**. I am trying to implement a notification system from the distributed caches (e.g Redis,MemCached, etc..) to the CacheManager instance. In the **documentation** it says that generally the distributed caches are the source of the **Backplane**... but I am not quite sure if **non distributed** caches can work as **Backplane** (I dont see the **point** in using local caches as Backplane system)

**Comment by MichaCo** [comment]
I'm not 100% sure I understand what you actually want to achieve.
You want to use non-distributed caches together with the backplane feature? Sure you can, I think there is nothing preventing you from setting any cache layer/type as the backplane source. 
The question is if it makes any sense to do that.

**Comment by TMiNus** [comment]
I didn't see the point neither on using non-distributed cache as Backplane. This was related with #58 because I was trying to set up an event framework so the cache manager instance could be notified if something happened with any handle. In my original design I needed to separate local caches from distributed caches mainly because some event didn't make sense on a non-distributed cache (e.g Disconnection event). 

By the way, if we set up a MemCached as backplane and we dont have a Redis handle configured, how the sync is done in this case without the Redis Pub/Sub

**Comment by MichaCo** [comment]
> By the way, if we set up a MemCached as backplane and we dont have a Redis handle configured, how is the sync done in this case without the Redis Pub/Sub

There is no alternative out of the box in CacheManager at the moment. 
MemCached doesn't come with the same features as Redis, meaning, I cannot use it as a Pub/Sub service.

Alternatives could be implemented using any message queue service or SignalR for example

**Comment by TMiNus** [comment]
That's pretty much my assumption, any alternative would need to depend of an external service that may or may not be there. I think this has to be expected giving the distribute nature of the sync feature

**Comment by MichaCo** [comment]
Sorry for the late answer, but I just wanted to state that JSON serialization is a lot slower than that manual "serialization". The Backplane message is more a protocol message with known variants, And I know exactly what the options and values can be, meaning, I don't see any reason to use the overhead of JSON for that
