### ISSUE TITLE
Redis deserialization throws if value type is loaded into the load-from assembly binding context

### ISSUE THREAD

**Issue by janmagnet** [MichaCo/CacheManager#61]
This call to [`Type.GetType(type)`](https://github.com/MichaCo/CacheManager/blob/dev/src/CacheManager.StackExchange.Redis/RedisValueConverter.cs#L177) returns `null` if the requested type is located in an assembly that has been loaded into the load-from binding context, as described in [this StackOverflow answer](http://stackoverflow.com/a/3142910). This causes an exception to be thrown by [`RedisValueConverter.Deserialize()`](https://github.com/MichaCo/CacheManager/blob/dev/src/CacheManager.StackExchange.Redis/RedisValueConverter.cs#L164) resulting in a failed deserialization.

This is an issue you can run into when dynamically loading assemblies e.g. as plugins with the Managed Extensibility Framework (MEF) or by using [`Assembly.LoadFrom()`](https://msdn.microsoft.com/en-us/library/1009fa28(v=vs.110).aspx) directly with assembly paths outside the probing path.

As a fallback when `Type.GetType()` returns `null`, we could loop through all assemblies using `AppDomain.CurrentDomain.GetAssemblies()` and for each `assembly` call [`assembly.GetType(typeName)`](https://msdn.microsoft.com/en-us/library/y0cd10tb(v=vs.110).aspx) until we find what we are looking for. Note that `typeName` must only contain the namespace and type name, and cannot contain the assembly name, so some kind of string manipulation would be required. Regex anyone? :) I would hazard to guess that a potential solution like this won't work for DNX. But then again, this problem might not be present in that environment to begin with.

Some other libraries use either `typeof(T)` on a generic parameter they are provided with, or at some point they get hold of the assembly where the type was defined, and call `GetType(typeName)` directly on that. Maybe there are ways one of these could be incorporated here as well?

There are also several ways to solve this problem in the calling application, but they all come with various disadvantages and quirks, so I've found that it's best to avoid them, if at all possible:

1. Modifying the probing path [via config](https://msdn.microsoft.com/en-us/library/823z9h8w%28v=VS.110%29.aspx). This requires knowledge of all plugin paths prior to application startup.
2. Updating the probing path in application code using the obsolete [`AppDomain.AppendPrivatePath()`](https://msdn.microsoft.com/en-us/library/system.appdomain.appendprivatepath(v=vs.110).aspx) method.
3. Spinning up a new AppDomain with the [`AppDomainSetup.PrivateBinPath`](https://msdn.microsoft.com/en-us/library/system.appdomainsetup.privatebinpath(v=vs.110).aspx) property pointing to the plugin paths.
4. Implementing the [`AppDomain.AssemblyResolve`](https://msdn.microsoft.com/en-us/library/system.appdomain.assemblyresolve%28v=vs.110%29.aspx) event to load assemblies manually. Locks the assemblies preventing shadow copying when running in an IIS process.
5. Only place plugins in the default probing paths.

Check out [this minimal solution](https://github.com/MichaCo/CacheManager/files/296063/cachemanager-mef-redis-repro.zip) (zip-file) which reproduces this problem (the Redis connection string must be adjusted).

**Comment by MichaCo** [comment]
yeah, good point. Problem is that <T> can be `object` and in that case I store the actual object type so that I can properly deserialize it. Otherwise that wouldn't work at all...

I will look into that if I find some time though. Lets see

**Comment by MichaCo** [comment]
@janmagnet That's actually an issue with the binary serializer not CacheManager it seems.
If you use Json serialization, it just works for me. Could you try that and let me know how it goes?

I added the Json serialization package to the Plugin project and changed the configuration like that:

    ICacheManager<MyPluginType> cache = CacheFactory.Build<MyPluginType>(p => p
        .WithJsonSerializer()
        .WithRedisConfiguration("redis", "...")
        .WithRedisCacheHandle("redis", true));

Thanks

**Comment by janmagnet** [comment]
You are correct. The issue is only related to the default binary serializer. Serializing with JSON seems to be working fine.

**Comment by MichaCo** [comment]
Ok cool, then I'll close this issue. I'm not planning to figure out how to work around this from the CacheManager perspective with the .NET binary serializer. You already gave a workaround for that and JSON serialization is faster, too, anyways ;)
