### ISSUE TITLE
InvalidCastException: Object must implement IConvertible when using Get method with interface as type

### ISSUE THREAD

**Issue by alexanderar** [MichaCo/CacheManager#62]
I have a pretty simple scenario:

1. Repo class that returns a `IList<SomeDto>` items
```
public class Repo
{
      public IList<SomeDto> Get()
      {
           return new List<SomeDto>();
      }
}
```
2. service class that has a ICacheManager<object> and uses it to cache the repo result:

```
public class Service
{
      private ICacheManager<object> _cacheManager;

      private Repo _repo;
      
      public Service(ICacheManager<object> cacheManager, Repo repo)
      {
            this._cacheManager = cacheManager;
            this._repo = repo;
      }

      public  IList<SomeDto> Get()
      {
             var items =  this._cacheManager.Get< IList<SomeDto>>("items");
             if(items == null)
             {
                   items = this._repo.Get();
                   this._cacheManager.Add("items",items);
              }
              return items;
      }
}
```

After cache has been instantiated with items
 `this._cacheManager.Get< IList<SomeDto>>("items")` throws an `InvalidCastException: Object must implement IConvertible`, while if I change it to 
`this._cacheManager.Get<List<SomeDto>>("items")` -- notice `List` instead of `IList` -- the cache works as expected.

My question is whether it is possible to use interfaces/base classes to retrieve items from cache.

Thanks in addvance

Alex

**Comment by MichaCo** [comment]
yup can be changed so that the converting Get<T> method supports that
