### ISSUE TITLE
support configured from xml string

### ISSUE THREAD

**Issue by jrt324** [MichaCo/CacheManager#65]
Web Application deploy  Cluster  behind Load Balancing ,some times we using a database store config settings without using config file,

so if we store this config xml segment into db ,all web server read xml config apply to cacheManager:

``` xml
<cacheManager.Redis>
  <connections>
    <connection id="redisLevel" database="5">
      <endpoints>
        <endpoint host="jwsoft-server2" port="6379" />
      </endpoints>
    </connection>
  </connections>
</cacheManager.Redis>

<cacheManager xmlns="http://tempuri.org/CacheManagerCfg.xsd">
  <managers>
    <cache name="defaultCache" updateMode="Up" enableStatistics="false" enablePerformanceCounters="false" backplaneName="redisLevel" backplaneType="CacheManager.Redis.RedisCacheBackplane, CacheManager.StackExchange.Redis" serializerType="CacheManager.Serialization.Json.JsonCacheSerializer,CacheManager.Serialization.Json">
      <handle name="firstLevel" ref="systemRuntimeHandle" expirationMode="Sliding" timeout="20s" />
      <handle name="redisLevel" ref="redisHandle" expirationMode="None" isBackplaneSource="true" />
    </cache>
  </managers>

  <cacheHandles>
    <handleDef id="systemRuntimeHandle" type="CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1, CacheManager.SystemRuntimeCaching" defaultExpirationMode="Sliding" defaultTimeout="5m" />
    <handleDef id="redisHandle" type="CacheManager.Redis.RedisCacheHandle`1, CacheManager.StackExchange.Redis" defaultExpirationMode="Absolute" defaultTimeout="5m" />
  </cacheHandles>
</cacheManager>
```

Is there any way to support this?

**Comment by MichaCo** [comment]
I added Microsoft.Extensions.Configuration based support, with that, it should be possible pretty easily. You can either write a configuration provider for your database or construct config sections in the way CacheManager understands it.
Or you simply use the "by code" configuration option of CacheManager, read your DB configuration and construct whatever is needed.
So, as you can see, I think there are a lot and enough options to configure CacheManager already, I'm not planning to add anything more right now.
And you should be able to accomplish your idea with some custom code I think.

Let me know how it goes or if you find any obstacles ;)

**Comment by MichaCo** [comment]
@jrt324 closing this one for now, let me know if you still having issues solving this...
