### ISSUE TITLE
in memory cache checking backplane as well

### ISSUE THREAD

**Issue by bigerock** [MichaCo/CacheManager#66]
if i'm using a multi-level cache, in-memory and redis for example, using redis as the backplane, why does it check at both levels during a get operation? this is costly and defeats the purpose of having an in-memory caching mechanism due to the synchronous nature of it. of course, perhaps i'm using it incorrectly?

i've noticed in the BaseCacheManager.cs > GetCacheItemInternal method (line 1023 in my code), it's doing a for loop on each cache handle when doing a get operation. this is where it should only check the in-memory cache and return a value if found. the backplane should already be subscribed to the deltas of the cache object via redis pub/sub. 

these are my assumptions and i'm sure i must be doing something wrong, so please correct me if so.

btw, here's how i'm instantiating the cachemanager object:

var ret = CacheFactory.Build("memandrediscache", settings =>
            {
                settings
                .WithSystemWebCacheHandle("inProcessCache")
                .And
                .WithRedisConfiguration(redisKey, config => config
                   .WithAllowAdmin()
                   .WithConnectionTimeout(1000)
                   .WithEndpoint(endPointUrl, endPointPort)
                   .WithPassword(password)               
                )
                .WithJsonSerializer(jsonSer, jsonDeSer)
                .WithMaxRetries(10) 
                .WithRetryTimeout(100)
                .WithRedisBackplane(redisKey)
                .WithRedisCacheHandle(redisKey, true);
            });

**Comment by MichaCo** [comment]
It for sure does not check both cache levels if it doesn't have to.
In the loop, if it finds the cache item in the first handle (in your case the in-process cache), it will not loop further (`break` statement a little bit further down below, same method).

**Comment by TMiNus** [comment]
In the write operations it will iterate backwards on your handles,in the retrieve operations it will iterate normally breaking when it finds the key in any handle

**Comment by bigerock** [comment]
ok i do see the break point. must be something else happening in my code.
