### ISSUE TITLE
Add support for Microsoft.Extensions.Caching.Memory

### ISSUE THREAD

**Issue by AuroraDysis** [MichaCo/CacheManager#67]
I just copy from CacheManager.SystemRuntimeCaching and change some things.
[Microsoft.Extensions.Caching.Memory](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Memory/1.0.0-rc2-final)
[my code](https://gist.github.com/AuroraDysis/2cd61d66225ae48db1c419b1a63207b5)

If you want to add it, I can submit a PR.

**Comment by MichaCo** [comment]
Sure, submit a PR! Looks very good :+1: ;)

Please, just make sure it does pass the unit tests, so at least add it to https://github.com/MichaCo/CacheManager/blob/dev/test/CacheManager.Tests/BaseCacheManagerTest.cs#L297 which is used in many tests.

**Comment by MichaCo** [comment]
will work on your PR #68 next, whenever I find some more time ~~

**Comment by MichaCo** [comment]
PR #68 has now finally been merged. Sorry for the delay and thanks a lot again!
I also changed the deps to use the released dotnet core bits
