### ISSUE TITLE
redis connection cannot auto close when ICacheManager created

### ISSUE THREAD

**Issue by icsharp** [MichaCo/CacheManager#72]
I used `CacheManager.StackExchange.Redis` component in my project(I created repository [CacheManager.Serialization.fastJSON ](https://github.com/icsharp/CacheManager.Serialization.fastJSON) for fastJSON to serialize cache object) ,and I found a problem the singleton object `ICacheManager<TCacheValue>` obtain a redis connection. So large amounts of redis connections would be created/open When many caches built to using ``ICacheManager<TCacheValue>`.
If redis connections cannot be auto closed, my redis server load will be quite heavily. Here is my code expample:
``` csharp
//redis connection will be open and not auto close
 ICacheManager<List<MyClass1>> objCache1 = CacheFactory.FromConfiguration<List<MyClass1>>("cache1", cfg);
  ICacheManager<List<MyClass2>>objCache2 = CacheFactory.FromConfiguration<List<MyClass2>>("cache2", cfg);
  ICacheManager<List<MyClass3>>objCache3 = CacheFactory.FromConfiguration<List<MyClass3>>("cache3", cfg);
  ICacheManager<List<MyClass4>>objCache4 = CacheFactory.FromConfiguration<List<MyClass4>>("cache3", cfg);
```
In my code,it will be created 4 redis connections until then application exit. Is there a way to share redis connection whenever large amouts of singleton object `ICacheManager<TCacheValue>` created/open?

**Comment by MichaCo** [comment]
As long as the configuration to Redis is the same, the connection will be shared

**Comment by icsharp** [comment]
@MichaCo 
For example, the redis connection canbe shared between ```ICacheManager<List<MyClass1>>``` and ```ICacheManager<List<MyClass2>>``` ? In my test case,it will create 2 connections, maybe something wrong with the configuration?
``` csharp
var cfg = ConfigurationBuilder.BuildConfiguration(settings =>
            {
                settings.WithUpdateMode(CacheUpdateMode.Up)
                        .WithRedisConfiguration("redis", config =>
                        {
                            config.WithAllowAdmin()
                            .WithDatabase(0)
                            .WithEndpoint("localhost", 6379);
                        })
                        .WithMaxRetries(100)
                        .WithRetryTimeout(50)
                        //.WithfastJSONSerializer(new JSONParameters
                        //{
                        //  UseEscapedUnicode = false,
                        //  UseExtensions = false,
                        //  EnableAnonymousTypes = true
                        //})
                        .WithGzJsonSerializer(new JSONParameters
                        {
                            UseEscapedUnicode = false,
                            UseExtensions = false,
                            EnableAnonymousTypes = true
                        })
                        .WithRedisBackplane("redis")
                        .WithRedisCacheHandle("redis", true);
            });
 ICacheManager<List<MyClass1>> objCache1 = CacheFactory.FromConfiguration<List<MyClass1>>("cache1", cfg);
  ICacheManager<List<MyClass2>>objCache2 = CacheFactory.FromConfiguration<List<MyClass2>>("cache2", cfg);
```
I pass the same params ```cfg``` to ```CacheFactory.FromConfiguration``` for objCache1  and objCache2, actually it will create two redis connections.

**Comment by MichaCo** [comment]
@icsharp thanks for the details.
Yes, all cache manager instances which share the exact same redis configuration will share the same `ConnectionMultiplexer` from StackExchange.Redis. 
The `ConnectionMultiplexer` handles the actual connections to the server, meaning, all I can do is ensure all CacheManager instance use the same multiplexer.

The multiplexer might open 2 connections, so, don't just rely on open connections on the redis server, there might be two even for one instance of CacheManager.

The code which ensures only one Multiplexer is used [can be found here](https://github.com/MichaCo/CacheManager/blob/master/src/CacheManager.StackExchange.Redis/RedisConnectionManager.cs#L87)

I cannot reproduce your findings, so can you tell me how you test that each instance opens a new connection?

**Comment by icsharp** [comment]
@MichaCo 
Thanks for your reply.

[My test](https://github.com/icsharp/CacheManager.Serialization.fastJSON/blob/master/src/fastJSON.Samples/Program.cs) is very simple ,just create two CacheManager instances and two redis connection created. But that is not enough to reproduce.

Your mean that ```ConnectionMultiplexer ``` maintains the redis connection pool, it is nothing with the ```CacheManager``` whenever how much instances created. So large amounts of ```CacheManager``` instances maybe share one or more redis connections from  ```ConnectionMultiplexer ```.

Thanks again for tell me the mechanism to ```CacheManager```. O(∩_∩)O~

**Comment by MichaCo** [comment]
Yeah as I said, I did a quick test, pretty similar to yours, created a configuration and created 6 CacheManager instances from it. All of them where in fact using the same Multiplexer and only created 2 client connections to the Redis server.
So, for me that works just fine ;)
