### ISSUE TITLE
EventLog api is not working

### ISSUE THREAD

**Issue by hariharanpalani** [MichaCo/CacheManager#75]
I tried to configure the Microsoft.Extensions.Logging.EventLog with all the dependencies. But, it is not working. I am getting following exception.

System.TypeLoadException: System.TypeLoadException: Could not load type 'Microsoft.Extensions.Logging.Logger`1' from assembly 'Microsoft.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'..

I am using 1.0.0-rc2-final verion

**Comment by MichaCo** [comment]
There is currently no released version of CacheManager which supports RC2 or release 1.0 of .net core stuff. See #37.
