### ISSUE TITLE
Cache not expiring

### ISSUE THREAD

**Issue by stevewash123** [MichaCo/CacheManager#76]
I'm creating my cache as follows.  I've set the constant ExpirationMins = 3.

evalCache = CacheFactory.Build<List<CandidateEvaluationSummaryResource>>(p =>
    p.WithSystemRuntimeCacheHandle()
      .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes(ExpirationMins)));

I let the system idle for 10 mins before refreshing my page but the cache did not expire.  Is there something else I need to do?  I also tried the DictionaryHandle with the same result.

**Comment by MichaCo** [comment]
I'm pretty sure the expiration, in general, works. There are unit tests and such.
It depends on how/where you use your cache. Maybe that instance you created is not used by the page and it is a mistake somewhere.
Maybe something refreshes the timeout => sliding means, it only expires if there is nothing accessing the cached key for more than 3 minutes.

Try maybe `absolute` expiration mode and see if that works

**Comment by stevewash123** [comment]
I set it to absolute and it worked.  I double checked, and it turned out there was another page using the same API endpoint.  Thanks for your quick and helpful response, apologies for the false error report.

**Comment by MichaCo** [comment]
np ;)
