### ISSUE TITLE
System.NullReferenceException in RedisCacheHandle

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#77]
I am getting a very weird null reference exception on the redis cache handle when the redis serves goes down, the exception actually comes from StackExchange.Redis. I tried to reproduce the exception outside of redis cache handle using StackExchange.Redis directly but when the connection goes down I am only getting RedisConnectionExceptions as it should be.

The specific section that is throwing the exception is...

``` charp
var setResult = this.connection.Database.HashSet(fullKey, HashFieldValue, value, when, flags);
```

I know this is wrapped under the Retry functionality which capture the RedisConnectionExceptions but for some reason StackExchange.Redis is throwing a null reference exception here in all the cases that I have tried

**Edit:** Is not an exception that shows in 100% of the cases but it is definitely there. I haven't found a way to reproduce it effectively beyond disconnecting and reconnecting the redis server

**Edit 2:** Right now I have managed to reproduce the error outside redis cache handle after disconnecting and reconnecting the redis server a couple of times. I will use the internal error event to try and see what is going on inside StackExchangeRedis. It would be nice if I had an external confirmation that this null reference exception is indeed happening

**Edit 3:** Maybe fixed with StackExchange/StackExchange.Redis#424 although is not the same call I suspect it is related

**Comment by MichaCo** [comment]
Actually, it sounds like exactly the issue which is already tracked in the StackExchange.Redis repository.

I cannot do anything in that regards unfortunately, NullRef exception should never occur.

**Comment by MichaCo** [comment]
@TMiNus Is that issue still a thing or can I close this for now?

**Comment by TMiNus** [comment]
you can close it @MichaCo
