### ISSUE TITLE
CacheManager with Couchbase.

### ISSUE THREAD

**Issue by simcard** [MichaCo/CacheManager#82]
Hi Guys,

Can someone please send me the code sample of cachemanger with couchbase...please

Thanks.

**Comment by MichaCo** [comment]
The configuration is done via couchbase configuration section and web/app.config
See the couchbase docu for that one or e.g. the unit tests [app.config](https://github.com/MichaCo/CacheManager/blob/dev/test/CacheManager.Tests/app.config)

Apart from that, that's more a question for stackoverflow and not an issue ;)
Thanks
M
