### ISSUE TITLE
question about GetOrAdd() interface design

### ISSUE THREAD

**Issue by naymore** [MichaCo/CacheManager#84]
**Interface design:** I'm not getting why it is GetOrAdd(string key, string region, Func<**string, string, TCacheValue**> valueFactory) rather than just  Func<**T**> - I usually use something like that: 

> T Get<*T*>(string key, Func<*T*> getData, TimeSpan slidingExpiration, string dependencyKey = null, EvictionPolicy evictionPolicy = EvictionPolicy.Default);

Which can then be used as simple as...
> cache.Get<*T*>(key, () => CreateType(i, x, y, z), "devices");

Why do I need to pass in two strings? I assume it's the cache key and the region?
Or am I using it the wrong way?

> Device device = _cacheManager.GetOrAdd(deviceIdString, "DeviceConfiguration", valueFactory: (a, b) => CreateDevice(deviceId));

**Comment by MichaCo** [comment]
Usually, if you need the region and key to factor the object the factory should return, its pretty convenient to not have to store it elsewhere...

Yeah, if you use the key+region API, you just have to create an arrow function with two string parameters.
You don't have to use them and writing `(a, b)=>bla` isn't too bad right?

Imagine you have logic in the factory which needs the key to identify the object:

`var obj = cache.GetOrAdd("myKey", () => storage.GetByKey("myKey"));`

In the example above, I have to write the key twice which is smelly code.

Or, I can store the key in a variable, but that's more code to write and somewhat messy. Also, it doesn't enforce consistency, you might use a totally different variable in both places...

```
var key = "myKey";
var obj = cache.GetOrAdd(key, () => storage.GetByKey(key));
```

Instead, it is much cleaner to pass through the key (and region) and just use it to retrieve the object. 

`var obj = cache.GetOrAdd("myKey", (k) => storage.GetByKey(k));`

Anyways, if you don't like it feel free to write your own extension method and use that instead ;)
