### ISSUE TITLE
Add a custom cache provider

### ISSUE THREAD

**Issue by grendo** [MichaCo/CacheManager#85]
Hi,
  great lib.  I wanted to add a custom cache provider based that uses an inhouse cache system we have.  Could you give me a pointer which interfaces I have to impliment to achieve this ?

**Comment by TMiNus** [comment]
From the top of my head (dont have the pc in front of me...) You will need to implement mainly the abstract class  *BaseCacheHandle*, in there you will overwritte *GetInternal* for example to your own Get for your cache and so on..

**Comment by MichaCo** [comment]
Hi,
Thanks!

Yeah that should be relatively straight forward. Look at the [dictionary cache handle](https://github.com/MichaCo/CacheManager/blob/dev/src/CacheManager.Core/Internal/DictionaryCacheHandle.cs) for example, should be the most simple one.

You have to extend from BaseCacheHandle<T> and implement the abstract methods at least.
If you system is a distributed cache you might have to add more details to the update method for example
