### ISSUE TITLE
How to register for Expiration of Cache item

### ISSUE THREAD

**Issue by brettveenstra** [MichaCo/CacheManager#88]
Been trying to use your library and can't seem to hook into the "expiration" process.

I've hooked up OnAdd, OnUpdate, OnClear, OnRemove but when my cache item expires, I can't find the handler for Expiration of a CacheItem.

**Comment by MichaCo** [comment]
Well it doesn't exist ;)
Some in memory caches, like System.Runtime stuff, does have that. If you totally need it, just use that one.
But out of process caches like Redis do not come with that feature. Meaning there is no way to provide that as a base feature.
