### ISSUE TITLE
Async Support?

### ISSUE THREAD

**Issue by bryanerayner** [MichaCo/CacheManager#89]
Is there any plans to add Async support to this library? While it may be that not all providers support Async, some do. Currently, this will be the only part of our application that is not Async, and I'd really like to be able to have Async all the way through.

**Comment by MichaCo** [comment]
I tried it once, it was a complete mess. 
Mostly because only redis would really be async because of the client implementation. Everything else would have to deal with async over sync issues...

It also doesn't really make any sense for in memory caches. Tasks also has some overhead and slows down the whole thing. 
That's why I did not add it.

**Comment by bryanerayner** [comment]
Ah, thanks for the reasoning behind that. When something is Put into the Cache, and synchronized with Redis, is that synchronization with Redis using blocking IO, or deferring the synchronization to a background thread?

**Comment by MichaCo** [comment]
Great question. `Add` uses blocking to verify if the operation was actually successful or not, `Put` doesn't block.
So if you want to put a lot of data quickly and don't care if it is there already or not, use `Put`.

**Comment by TMiNus** [comment]
Probably it should be relevant to mention the flag *FireandForget* that the operations of Redis use. It is a form of async calls designed  by StackExchange.Redis

**Comment by bryanerayner** [comment]
Thanks so much for the clarification on both fronts!

**Comment by srivathsah** [comment]
@MichaCo I think it is a good suggestion to have async support by default, I get your point about in-memory caches and libraries that dont suport it, For these kind of scenarios I suggest that having ValueTask<T> as the return type instead of Task<T>
