### ISSUE TITLE
Is there a .net core / Redis example?

### ISSUE THREAD

**Issue by shayden** [MichaCo/CacheManager#91]
Do you have an example of using Redis with CacheManager.Core?  The sample project has redis support ifdef'ed out.

Thanks

**Comment by MichaCo** [comment]
Unit tests and my [playground test project](https://github.com/MichaCo/CacheManager/tree/dev/test/CacheManager.Config.Tests) uses Redis.

The implementation relies on StackExchange.Redis, there is no official release for .NET core yet, so, CacheManager also relies on that...
That being said, my unit tests totally work find during the .NET Core build for example (on Windows).

**Comment by shayden** [comment]
Don't know why I didn't think to look there. Thanks!
