### ISSUE TITLE
Problem retrieving cache item with ExpirationMode.None

### ISSUE THREAD

**Issue by sam-piper** [MichaCo/CacheManager#97]
Hi, I've stumbled on a problem with the memory cache handle, maybe it's a bug, maybe it's intended, but I need to get more information on it. I'm using version 0.9.1.

This code reproduces the problem:

```
var cache = CacheFactory.Build("CacheManager", settings =>
{
     settings.WithSystemRuntimeCacheHandle()
                 .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes(30));
});

cache.Put(new CacheItem<object>("AAA", 1, ExpirationMode.None, TimeSpan.FromMinutes(0)));
var item = cache.GetCacheItem("AAA");
```

The cache item is being returned with a mode of Sliding and a timeout of 30 minutes, which is not what I expect at all - I expect the cache item to have the same values when the item was set.

Have I misunderstood something here, or is this a bug? If it's by design, it's quite confusing as I'm unsure if `ExpirationMode.None` is working as intended.

**Comment by MichaCo** [comment]
Yup that's actually a bug

**Comment by sam-piper** [comment]
Cool, thanks, I'll work around it for now.

**Comment by MichaCo** [comment]
This is fixed in next release

**Comment by MichaCo** [comment]
@sam-piper 
Version 0.9.2 is out and should fix this issue. Let me know if that's not the case though ;)
