### ISSUE TITLE
Problem with GetOrAdd() and null values from value factory

### ISSUE THREAD

**Issue by sam-piper** [MichaCo/CacheManager#99]
Hi,

I'm running into a big problem using the `GetOrAdd()` method on `ICacheManager<object>`. 

Sometimes a value factory supplied to this method will return a null reference, because the underlying data has been removed, for example. This crashes the code with an `ArgumentNullException` because the `CacheItem` constructor won't allow a null value.

Would it be possible for the underlying implementation to invoke the value factory and only set the cache item if the value from the factory is not null, otherwise just return null so that the calling code can just continue? 

I understand why we don't want to set a null value in the underlying cache, but it should be possible to handle null from a value factory as this can easily happen.

Otherwise I guess I would have to look at a special value to represent null which is also cacheable, but that's not ideal.

If there's a better solution that I'm missing, happy to hear it.

Thanks,

Sam

**Comment by MichaCo** [comment]
@sam-piper  Good question. The problem is, that the intention of the `GetOrAdd` method is to ensure a value is stored in the cache at the end (and gets returned).

If the method would return null, it could mean different things and you'd have to always react on it.

If the value factory for some reason returns null, that's basically an invalid application state, right? And should either not happen, or, if you expect it to happen, you'd have to handle it.

Unfortunately there is no simple way to cancel the operation and do something reasonable ;)

What about you add a try/catch for ArgumentNull around it. Make it an extension e.g. `TryGetOrAdd` if you don't want to write that code every time.

Does that make sense? Let me know what you think.

**Comment by sam-piper** [comment]
Thanks for the reply!

I think that a value factory should be able to return null without causing exceptions - I don't think that the underlying caching layer should have to constrain its implementation either, it's just a black box.

For example say I'm processing a web request that references a cached entity graph which is not currently in the cache and has just been deleted by another request on another server - the code uses GetOrAdd as a way of saying, look in the cache, if it's not there then invoke the function that loads it from the database, cache that value and return it. The database will return a null reference if the entity no longer exists, and the code expects this value to be passed through the caching layer regardless.

This isn't exceptional in my opinion, it's just standard data access, but becomes difficult to handle with the current implementation here.

Using try/catch would work around the issue I'm having, but to me it feels a bit hacky - I'd like to see the underlying framework be more flexible here, ideally.

Sent from my iPhone

On 18 Oct 2016, at 6:49 PM, MichaC <notifications@github.com<mailto:notifications@github.com>> wrote:


@sam-piper<https://github.com/sam-piper> Good question. The problem is, that the intention of the GetOrAdd method is to ensure a value is stored in the cache at the end (and gets returned).

If the method would return null, it could mean different things and you'd have to always react on it.

If the value factory for some reason returns null, that's basically an invalid application state, right? And should either not happen, or, if you expect it to happen, you'd have to handle it.

Unfortunately there is no simple way to cancel the operation and do something reasonable ;)

What about you add a try/catch for ArgumentNull around it. Make it an extension e.g. TryGetOrAdd if you don't want to write that code every time.

Does that make sense? Let me know what you think.

-

**Comment by MichaCo** [comment]
I agree that an exception is less simple to deal with than null. But you'd have to check for null in that case.

My concern was that returning null could mean different things, which would be misleading in what failed or what the result actually means.
In the case of GetOrAdd, returning null would mean that the key doesn't exist and add did not work for whatever reason. That's kind of fine, but if you don't expect null and want to know why, the debug process would be kind of annoying. I usually prefer in a more explicit API which is easier to understand why something happens...

Update works similar, although there are some catches. If the update valueFactory returns null, it will throw an error. In case they key didn't exist at all, it will return null. I already have mixed feelings about that returning null... 
If I would also return null in case valueFactory returns null, it would be even more confusing to figure out what happend.

So, for `Update` I will not change it for sure, but then the API should also be kind of consistent...

**Comment by sam-piper** [comment]
For now I'll use try/catch - I'm not anticipating that this problem will occur very often, so hopefully the number of exceptions generated is small, but again, handling a control flow issue by catching exceptions is not ideal.

I understand the difficulties around what null means. I personally think that GetOrAdd could be modified without needing to be consistent with other methods, as it works in a specific way and I think is very likely to be used orthogonally to other methods - just add a null check before creating and adding the internal cache item and the issue as I experience it is solved. This still stays in line with the rule that null values are not cached, and the calling code checks for null only if it needs to.

It's just a suggestion, I understand if this change conflicts with the way you've designed the API, but for me it is a bit dissonant with the way my own code is working, and I imagine others will encounter the same problem as well.

**Comment by MichaCo** [comment]
@sam-piper I thought about it a little bit more and the result is that I will add another method `TryGetOrAdd` to compensate. So, if you don't want to handle exceptions, use that one and it will return false in case your factory returns null. 
The method has an `out` parameter for the value (which in that case would also be null or default(T)).

The implementation doesn't throw/catch exceptions.

I always disliked the behavior of `Update` returning null in case the `key` doesn't exist. I also changed that to throw an exception now. There is already `TryUpdate` and `AddOrUpdate` in case you want to implement a certain app flow without exception handling.

So, those two methods are in line now in terms of behavior I think.

**Comment by MichaCo** [comment]
@sam-piper 
Version 0.9.2 is out and and changes mentioned above are in. Let me know if that solves your concerns or what you think. Thanks!

**Comment by PavelKn** [comment]
In my case it was necessary to cache null values. It was indicating "Not found" result.
And I found a simple solution:

```
public class NullableObject<T>
{
    public T Value { get; }

    private NullableObject(T value)
    {
        Value = value;
    }

    public static implicit operator T(NullableObject<T> nullableObject)
    {
        return nullableObject.Value;
    }

    public static implicit operator NullableObject<T>(T objectValue)
    {
        return new NullableObject<T>(objectValue);
    }
}
```

Code updates:

Throws ArgumentNullException exception on null values:
`private ICacheManager<ObjectToCache> _cache;`

Doesn't throw ArgumentNullException exception and returns back cached null values (without calling valueFactory method):
`private ICacheManager<NullableObject<ObjectToCache>> _cache;`
